// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

@Entity
@Table(name = "attendance")
public class Attendance {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gym_id", nullable = false)
    private Gym gym;
    @Column(nullable = false, updatable = false)
    private LocalDateTime checkInTime;

    @PrePersist
    public void prePersist() {
        this.checkInTime = LocalDateTime.now();
    }
public static class AttendanceBuilder {
private Long id;
private User user;
private Gym gym;
private LocalDateTime checkInTime;
AttendanceBuilder() {
        }
public Attendance.AttendanceBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public Attendance.AttendanceBuilder user(final User user) {
            this.user = user;
            return this;
        }
public Attendance.AttendanceBuilder gym(final Gym gym) {
            this.gym = gym;
            return this;
        }
public Attendance.AttendanceBuilder checkInTime(final LocalDateTime checkInTime) {
            this.checkInTime = checkInTime;
            return this;
        }
public Attendance build() {
            return new Attendance(this.id, this.user, this.gym, this.checkInTime);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "Attendance.AttendanceBuilder(id=" + this.id + ", user=" + this.user + ", gym=" + this.gym + ", checkInTime=" + this.checkInTime + ")";
        }
    }
public static Attendance.AttendanceBuilder builder() {
        return new Attendance.AttendanceBuilder();
    }
public Long getId() {
        return this.id;
    }
public User getUser() {
        return this.user;
    }
public Gym getGym() {
        return this.gym;
    }
public LocalDateTime getCheckInTime() {
        return this.checkInTime;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setUser(final User user) {
        this.user = user;
    }
public void setGym(final Gym gym) {
        this.gym = gym;
    }
public void setCheckInTime(final LocalDateTime checkInTime) {
        this.checkInTime = checkInTime;
    }
public Attendance() {
    }
public Attendance(final Long id, final User user, final Gym gym, final LocalDateTime checkInTime) {
        this.id = id;
        this.user = user;
        this.gym = gym;
        this.checkInTime = checkInTime;
    }
}
