// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.entity;

import com.fitconnect.entity.enums.EquipmentCondition;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

@Entity
@Table(name = "equipment")
public class Equipment {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gym_id", nullable = false)
    private Gym gym;
    @Column(nullable = false)
    private String equipmentName;
    @Column(nullable = false)
    private Integer quantity;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private EquipmentCondition condition;
public static class EquipmentBuilder {
private Long id;
private Gym gym;
private String equipmentName;
private Integer quantity;
private EquipmentCondition condition;
EquipmentBuilder() {
        }
public Equipment.EquipmentBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public Equipment.EquipmentBuilder gym(final Gym gym) {
            this.gym = gym;
            return this;
        }
public Equipment.EquipmentBuilder equipmentName(final String equipmentName) {
            this.equipmentName = equipmentName;
            return this;
        }
public Equipment.EquipmentBuilder quantity(final Integer quantity) {
            this.quantity = quantity;
            return this;
        }
public Equipment.EquipmentBuilder condition(final EquipmentCondition condition) {
            this.condition = condition;
            return this;
        }
public Equipment build() {
            return new Equipment(this.id, this.gym, this.equipmentName, this.quantity, this.condition);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "Equipment.EquipmentBuilder(id=" + this.id + ", gym=" + this.gym + ", equipmentName=" + this.equipmentName + ", quantity=" + this.quantity + ", condition=" + this.condition + ")";
        }
    }
public static Equipment.EquipmentBuilder builder() {
        return new Equipment.EquipmentBuilder();
    }
public Long getId() {
        return this.id;
    }
public Gym getGym() {
        return this.gym;
    }
public String getEquipmentName() {
        return this.equipmentName;
    }
public Integer getQuantity() {
        return this.quantity;
    }
public EquipmentCondition getCondition() {
        return this.condition;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setGym(final Gym gym) {
        this.gym = gym;
    }
public void setEquipmentName(final String equipmentName) {
        this.equipmentName = equipmentName;
    }
public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }
public void setCondition(final EquipmentCondition condition) {
        this.condition = condition;
    }
public Equipment() {
    }
public Equipment(final Long id, final Gym gym, final String equipmentName, final Integer quantity, final EquipmentCondition condition) {
        this.id = id;
        this.gym = gym;
        this.equipmentName = equipmentName;
        this.quantity = quantity;
        this.condition = condition;
    }
}
