// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "equipment_rental_transactions")
public class EquipmentRentalTransaction {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_owner_id", nullable = false)
    private User sellerOwner;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "buyer_owner_id", nullable = false)
    private User buyerOwner;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_gym_id", nullable = false)
    private Gym sellerGym;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "buyer_gym_id", nullable = false)
    private Gym buyerGym;
    @Column(nullable = false)
    private String equipmentName;
    @Column(length = 2000)
    private String details;
    @Column(nullable = false)
    private BigDecimal monthlyRentPrice;
    @Column(nullable = false, updatable = false)
    private LocalDateTime purchasedAt;

    @PrePersist
    public void prePersist() {
        this.purchasedAt = LocalDateTime.now();
    }
public static class EquipmentRentalTransactionBuilder {
private Long id;
private User sellerOwner;
private User buyerOwner;
private Gym sellerGym;
private Gym buyerGym;
private String equipmentName;
private String details;
private BigDecimal monthlyRentPrice;
private LocalDateTime purchasedAt;
EquipmentRentalTransactionBuilder() {
        }
public EquipmentRentalTransaction.EquipmentRentalTransactionBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public EquipmentRentalTransaction.EquipmentRentalTransactionBuilder sellerOwner(final User sellerOwner) {
            this.sellerOwner = sellerOwner;
            return this;
        }
public EquipmentRentalTransaction.EquipmentRentalTransactionBuilder buyerOwner(final User buyerOwner) {
            this.buyerOwner = buyerOwner;
            return this;
        }
public EquipmentRentalTransaction.EquipmentRentalTransactionBuilder sellerGym(final Gym sellerGym) {
            this.sellerGym = sellerGym;
            return this;
        }
public EquipmentRentalTransaction.EquipmentRentalTransactionBuilder buyerGym(final Gym buyerGym) {
            this.buyerGym = buyerGym;
            return this;
        }
public EquipmentRentalTransaction.EquipmentRentalTransactionBuilder equipmentName(final String equipmentName) {
            this.equipmentName = equipmentName;
            return this;
        }
public EquipmentRentalTransaction.EquipmentRentalTransactionBuilder details(final String details) {
            this.details = details;
            return this;
        }
public EquipmentRentalTransaction.EquipmentRentalTransactionBuilder monthlyRentPrice(final BigDecimal monthlyRentPrice) {
            this.monthlyRentPrice = monthlyRentPrice;
            return this;
        }
public EquipmentRentalTransaction.EquipmentRentalTransactionBuilder purchasedAt(final LocalDateTime purchasedAt) {
            this.purchasedAt = purchasedAt;
            return this;
        }
public EquipmentRentalTransaction build() {
            return new EquipmentRentalTransaction(this.id, this.sellerOwner, this.buyerOwner, this.sellerGym, this.buyerGym, this.equipmentName, this.details, this.monthlyRentPrice, this.purchasedAt);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "EquipmentRentalTransaction.EquipmentRentalTransactionBuilder(id=" + this.id + ", sellerOwner=" + this.sellerOwner + ", buyerOwner=" + this.buyerOwner + ", sellerGym=" + this.sellerGym + ", buyerGym=" + this.buyerGym + ", equipmentName=" + this.equipmentName + ", details=" + this.details + ", monthlyRentPrice=" + this.monthlyRentPrice + ", purchasedAt=" + this.purchasedAt + ")";
        }
    }
public static EquipmentRentalTransaction.EquipmentRentalTransactionBuilder builder() {
        return new EquipmentRentalTransaction.EquipmentRentalTransactionBuilder();
    }
public Long getId() {
        return this.id;
    }
public User getSellerOwner() {
        return this.sellerOwner;
    }
public User getBuyerOwner() {
        return this.buyerOwner;
    }
public Gym getSellerGym() {
        return this.sellerGym;
    }
public Gym getBuyerGym() {
        return this.buyerGym;
    }
public String getEquipmentName() {
        return this.equipmentName;
    }
public String getDetails() {
        return this.details;
    }
public BigDecimal getMonthlyRentPrice() {
        return this.monthlyRentPrice;
    }
public LocalDateTime getPurchasedAt() {
        return this.purchasedAt;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setSellerOwner(final User sellerOwner) {
        this.sellerOwner = sellerOwner;
    }
public void setBuyerOwner(final User buyerOwner) {
        this.buyerOwner = buyerOwner;
    }
public void setSellerGym(final Gym sellerGym) {
        this.sellerGym = sellerGym;
    }
public void setBuyerGym(final Gym buyerGym) {
        this.buyerGym = buyerGym;
    }
public void setEquipmentName(final String equipmentName) {
        this.equipmentName = equipmentName;
    }
public void setDetails(final String details) {
        this.details = details;
    }
public void setMonthlyRentPrice(final BigDecimal monthlyRentPrice) {
        this.monthlyRentPrice = monthlyRentPrice;
    }
public void setPurchasedAt(final LocalDateTime purchasedAt) {
        this.purchasedAt = purchasedAt;
    }
public EquipmentRentalTransaction() {
    }
public EquipmentRentalTransaction(final Long id, final User sellerOwner, final User buyerOwner, final Gym sellerGym, final Gym buyerGym, final String equipmentName, final String details, final BigDecimal monthlyRentPrice, final LocalDateTime purchasedAt) {
        this.id = id;
        this.sellerOwner = sellerOwner;
        this.buyerOwner = buyerOwner;
        this.sellerGym = sellerGym;
        this.buyerGym = buyerGym;
        this.equipmentName = equipmentName;
        this.details = details;
        this.monthlyRentPrice = monthlyRentPrice;
        this.purchasedAt = purchasedAt;
    }
}
