// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "equipment_rental_listings")
public class EquipmentRentalListing {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_owner_id", nullable = false)
    private User sellerOwner;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_gym_id", nullable = false)
    private Gym sellerGym;
    @Column(nullable = false)
    private String equipmentName;
    @Column(length = 2000)
    private String details;
    @Column(nullable = false)
    private BigDecimal monthlyRentPrice;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }
public static class EquipmentRentalListingBuilder {
private Long id;
private User sellerOwner;
private Gym sellerGym;
private String equipmentName;
private String details;
private BigDecimal monthlyRentPrice;
private LocalDateTime createdAt;
EquipmentRentalListingBuilder() {
        }
public EquipmentRentalListing.EquipmentRentalListingBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public EquipmentRentalListing.EquipmentRentalListingBuilder sellerOwner(final User sellerOwner) {
            this.sellerOwner = sellerOwner;
            return this;
        }
public EquipmentRentalListing.EquipmentRentalListingBuilder sellerGym(final Gym sellerGym) {
            this.sellerGym = sellerGym;
            return this;
        }
public EquipmentRentalListing.EquipmentRentalListingBuilder equipmentName(final String equipmentName) {
            this.equipmentName = equipmentName;
            return this;
        }
public EquipmentRentalListing.EquipmentRentalListingBuilder details(final String details) {
            this.details = details;
            return this;
        }
public EquipmentRentalListing.EquipmentRentalListingBuilder monthlyRentPrice(final BigDecimal monthlyRentPrice) {
            this.monthlyRentPrice = monthlyRentPrice;
            return this;
        }
public EquipmentRentalListing.EquipmentRentalListingBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }
public EquipmentRentalListing build() {
            return new EquipmentRentalListing(this.id, this.sellerOwner, this.sellerGym, this.equipmentName, this.details, this.monthlyRentPrice, this.createdAt);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "EquipmentRentalListing.EquipmentRentalListingBuilder(id=" + this.id + ", sellerOwner=" + this.sellerOwner + ", sellerGym=" + this.sellerGym + ", equipmentName=" + this.equipmentName + ", details=" + this.details + ", monthlyRentPrice=" + this.monthlyRentPrice + ", createdAt=" + this.createdAt + ")";
        }
    }
public static EquipmentRentalListing.EquipmentRentalListingBuilder builder() {
        return new EquipmentRentalListing.EquipmentRentalListingBuilder();
    }
public Long getId() {
        return this.id;
    }
public User getSellerOwner() {
        return this.sellerOwner;
    }
public Gym getSellerGym() {
        return this.sellerGym;
    }
public String getEquipmentName() {
        return this.equipmentName;
    }
public String getDetails() {
        return this.details;
    }
public BigDecimal getMonthlyRentPrice() {
        return this.monthlyRentPrice;
    }
public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setSellerOwner(final User sellerOwner) {
        this.sellerOwner = sellerOwner;
    }
public void setSellerGym(final Gym sellerGym) {
        this.sellerGym = sellerGym;
    }
public void setEquipmentName(final String equipmentName) {
        this.equipmentName = equipmentName;
    }
public void setDetails(final String details) {
        this.details = details;
    }
public void setMonthlyRentPrice(final BigDecimal monthlyRentPrice) {
        this.monthlyRentPrice = monthlyRentPrice;
    }
public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
public EquipmentRentalListing() {
    }
public EquipmentRentalListing(final Long id, final User sellerOwner, final Gym sellerGym, final String equipmentName, final String details, final BigDecimal monthlyRentPrice, final LocalDateTime createdAt) {
        this.id = id;
        this.sellerOwner = sellerOwner;
        this.sellerGym = sellerGym;
        this.equipmentName = equipmentName;
        this.details = details;
        this.monthlyRentPrice = monthlyRentPrice;
        this.createdAt = createdAt;
    }
}
