// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

@Entity
@Table(name = "gyms")
public class Gym {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String name;
    @Column(nullable = false)
    private String location;
    @Column(nullable = false)
    private Double monthlyFee;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "owner_id", nullable = false)
    private User owner;
public static class GymBuilder {
private Long id;
private String name;
private String location;
private Double monthlyFee;
private User owner;
GymBuilder() {
        }
public Gym.GymBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public Gym.GymBuilder name(final String name) {
            this.name = name;
            return this;
        }
public Gym.GymBuilder location(final String location) {
            this.location = location;
            return this;
        }
public Gym.GymBuilder monthlyFee(final Double monthlyFee) {
            this.monthlyFee = monthlyFee;
            return this;
        }
public Gym.GymBuilder owner(final User owner) {
            this.owner = owner;
            return this;
        }
public Gym build() {
            return new Gym(this.id, this.name, this.location, this.monthlyFee, this.owner);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "Gym.GymBuilder(id=" + this.id + ", name=" + this.name + ", location=" + this.location + ", monthlyFee=" + this.monthlyFee + ", owner=" + this.owner + ")";
        }
    }
public static Gym.GymBuilder builder() {
        return new Gym.GymBuilder();
    }
public Long getId() {
        return this.id;
    }
public String getName() {
        return this.name;
    }
public String getLocation() {
        return this.location;
    }
public Double getMonthlyFee() {
        return this.monthlyFee;
    }
public User getOwner() {
        return this.owner;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setName(final String name) {
        this.name = name;
    }
public void setLocation(final String location) {
        this.location = location;
    }
public void setMonthlyFee(final Double monthlyFee) {
        this.monthlyFee = monthlyFee;
    }
public void setOwner(final User owner) {
        this.owner = owner;
    }
public Gym() {
    }
public Gym(final Long id, final String name, final String location, final Double monthlyFee, final User owner) {
        this.id = id;
        this.name = name;
        this.location = location;
        this.monthlyFee = monthlyFee;
        this.owner = owner;
    }
}
