// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

@Entity
@Table(name = "gym_reviews")
public class GymReview {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gym_id", nullable = false)
    private Gym gym;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @Column(nullable = false)
    private Integer rating;
    @Column(nullable = false, length = 1000)
    private String comment;
    @Column(nullable = false)
    private LocalDateTime createdAt;
private static LocalDateTime $default$createdAt() {
        return LocalDateTime.now();
    }
public static class GymReviewBuilder {
private Long id;
private Gym gym;
private User user;
private Integer rating;
private String comment;
private boolean createdAt$set;
private LocalDateTime createdAt$value;
GymReviewBuilder() {
        }
public GymReview.GymReviewBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public GymReview.GymReviewBuilder gym(final Gym gym) {
            this.gym = gym;
            return this;
        }
public GymReview.GymReviewBuilder user(final User user) {
            this.user = user;
            return this;
        }
public GymReview.GymReviewBuilder rating(final Integer rating) {
            this.rating = rating;
            return this;
        }
public GymReview.GymReviewBuilder comment(final String comment) {
            this.comment = comment;
            return this;
        }
public GymReview.GymReviewBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt$value = createdAt;
            createdAt$set = true;
            return this;
        }
public GymReview build() {
            LocalDateTime createdAt$value = this.createdAt$value;
            if (!this.createdAt$set) createdAt$value = GymReview.$default$createdAt();
            return new GymReview(this.id, this.gym, this.user, this.rating, this.comment, createdAt$value);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "GymReview.GymReviewBuilder(id=" + this.id + ", gym=" + this.gym + ", user=" + this.user + ", rating=" + this.rating + ", comment=" + this.comment + ", createdAt$value=" + this.createdAt$value + ")";
        }
    }
public static GymReview.GymReviewBuilder builder() {
        return new GymReview.GymReviewBuilder();
    }
public Long getId() {
        return this.id;
    }
public Gym getGym() {
        return this.gym;
    }
public User getUser() {
        return this.user;
    }
public Integer getRating() {
        return this.rating;
    }
public String getComment() {
        return this.comment;
    }
public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setGym(final Gym gym) {
        this.gym = gym;
    }
public void setUser(final User user) {
        this.user = user;
    }
public void setRating(final Integer rating) {
        this.rating = rating;
    }
public void setComment(final String comment) {
        this.comment = comment;
    }
public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
public GymReview() {
        this.createdAt = GymReview.$default$createdAt();
    }
public GymReview(final Long id, final Gym gym, final User user, final Integer rating, final String comment, final LocalDateTime createdAt) {
        this.id = id;
        this.gym = gym;
        this.user = user;
        this.rating = rating;
        this.comment = comment;
        this.createdAt = createdAt;
    }
}
