// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.entity;

import com.fitconnect.entity.enums.MembershipStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDate;

@Entity
@Table(name = "memberships")
public class Membership {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gym_id", nullable = false)
    private Gym gym;
    @Column(nullable = false)
    private String planName;
    @Column(nullable = false)
    private Integer durationMonths;
    @Column(nullable = false)
    private LocalDate startDate;
    @Column(nullable = false)
    private LocalDate endDate;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private MembershipStatus status;
public static class MembershipBuilder {
private Long id;
private User user;
private Gym gym;
private String planName;
private Integer durationMonths;
private LocalDate startDate;
private LocalDate endDate;
private MembershipStatus status;
MembershipBuilder() {
        }
public Membership.MembershipBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public Membership.MembershipBuilder user(final User user) {
            this.user = user;
            return this;
        }
public Membership.MembershipBuilder gym(final Gym gym) {
            this.gym = gym;
            return this;
        }
public Membership.MembershipBuilder planName(final String planName) {
            this.planName = planName;
            return this;
        }
public Membership.MembershipBuilder durationMonths(final Integer durationMonths) {
            this.durationMonths = durationMonths;
            return this;
        }
public Membership.MembershipBuilder startDate(final LocalDate startDate) {
            this.startDate = startDate;
            return this;
        }
public Membership.MembershipBuilder endDate(final LocalDate endDate) {
            this.endDate = endDate;
            return this;
        }
public Membership.MembershipBuilder status(final MembershipStatus status) {
            this.status = status;
            return this;
        }
public Membership build() {
            return new Membership(this.id, this.user, this.gym, this.planName, this.durationMonths, this.startDate, this.endDate, this.status);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "Membership.MembershipBuilder(id=" + this.id + ", user=" + this.user + ", gym=" + this.gym + ", planName=" + this.planName + ", durationMonths=" + this.durationMonths + ", startDate=" + this.startDate + ", endDate=" + this.endDate + ", status=" + this.status + ")";
        }
    }
public static Membership.MembershipBuilder builder() {
        return new Membership.MembershipBuilder();
    }
public Long getId() {
        return this.id;
    }
public User getUser() {
        return this.user;
    }
public Gym getGym() {
        return this.gym;
    }
public String getPlanName() {
        return this.planName;
    }
public Integer getDurationMonths() {
        return this.durationMonths;
    }
public LocalDate getStartDate() {
        return this.startDate;
    }
public LocalDate getEndDate() {
        return this.endDate;
    }
public MembershipStatus getStatus() {
        return this.status;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setUser(final User user) {
        this.user = user;
    }
public void setGym(final Gym gym) {
        this.gym = gym;
    }
public void setPlanName(final String planName) {
        this.planName = planName;
    }
public void setDurationMonths(final Integer durationMonths) {
        this.durationMonths = durationMonths;
    }
public void setStartDate(final LocalDate startDate) {
        this.startDate = startDate;
    }
public void setEndDate(final LocalDate endDate) {
        this.endDate = endDate;
    }
public void setStatus(final MembershipStatus status) {
        this.status = status;
    }
public Membership() {
    }
public Membership(final Long id, final User user, final Gym gym, final String planName, final Integer durationMonths, final LocalDate startDate, final LocalDate endDate, final MembershipStatus status) {
        this.id = id;
        this.user = user;
        this.gym = gym;
        this.planName = planName;
        this.durationMonths = durationMonths;
        this.startDate = startDate;
        this.endDate = endDate;
        this.status = status;
    }
}
