// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.entity;

import com.fitconnect.entity.enums.PaymentStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "payments")
public class Payment {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gym_id", nullable = false)
    private Gym gym;
    @Column(nullable = false)
    private BigDecimal amount;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PaymentStatus status;
    @Column(nullable = false, updatable = false)
    private LocalDateTime paidAt;

    @PrePersist
    public void prePersist() {
        this.paidAt = LocalDateTime.now();
    }
public static class PaymentBuilder {
private Long id;
private User user;
private Gym gym;
private BigDecimal amount;
private PaymentStatus status;
private LocalDateTime paidAt;
PaymentBuilder() {
        }
public Payment.PaymentBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public Payment.PaymentBuilder user(final User user) {
            this.user = user;
            return this;
        }
public Payment.PaymentBuilder gym(final Gym gym) {
            this.gym = gym;
            return this;
        }
public Payment.PaymentBuilder amount(final BigDecimal amount) {
            this.amount = amount;
            return this;
        }
public Payment.PaymentBuilder status(final PaymentStatus status) {
            this.status = status;
            return this;
        }
public Payment.PaymentBuilder paidAt(final LocalDateTime paidAt) {
            this.paidAt = paidAt;
            return this;
        }
public Payment build() {
            return new Payment(this.id, this.user, this.gym, this.amount, this.status, this.paidAt);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "Payment.PaymentBuilder(id=" + this.id + ", user=" + this.user + ", gym=" + this.gym + ", amount=" + this.amount + ", status=" + this.status + ", paidAt=" + this.paidAt + ")";
        }
    }
public static Payment.PaymentBuilder builder() {
        return new Payment.PaymentBuilder();
    }
public Long getId() {
        return this.id;
    }
public User getUser() {
        return this.user;
    }
public Gym getGym() {
        return this.gym;
    }
public BigDecimal getAmount() {
        return this.amount;
    }
public PaymentStatus getStatus() {
        return this.status;
    }
public LocalDateTime getPaidAt() {
        return this.paidAt;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setUser(final User user) {
        this.user = user;
    }
public void setGym(final Gym gym) {
        this.gym = gym;
    }
public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }
public void setStatus(final PaymentStatus status) {
        this.status = status;
    }
public void setPaidAt(final LocalDateTime paidAt) {
        this.paidAt = paidAt;
    }
public Payment() {
    }
public Payment(final Long id, final User user, final Gym gym, final BigDecimal amount, final PaymentStatus status, final LocalDateTime paidAt) {
        this.id = id;
        this.user = user;
        this.gym = gym;
        this.amount = amount;
        this.status = status;
        this.paidAt = paidAt;
    }
}
