// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import java.time.LocalDate;

@Entity
@Table(name = "streaks")
public class Streak {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;
    @Column(nullable = false)
    private Integer streakCount;
    @Column(nullable = false)
    private Integer pauseTokensRemaining;
    @Column(nullable = false)
    private LocalDate lastActivityDate;
    @Column(nullable = false)
    private Integer pauseResetMonth;
    @Column(nullable = false)
    private Integer pauseResetYear;
public static class StreakBuilder {
private Long id;
private User user;
private Integer streakCount;
private Integer pauseTokensRemaining;
private LocalDate lastActivityDate;
private Integer pauseResetMonth;
private Integer pauseResetYear;
StreakBuilder() {
        }
public Streak.StreakBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public Streak.StreakBuilder user(final User user) {
            this.user = user;
            return this;
        }
public Streak.StreakBuilder streakCount(final Integer streakCount) {
            this.streakCount = streakCount;
            return this;
        }
public Streak.StreakBuilder pauseTokensRemaining(final Integer pauseTokensRemaining) {
            this.pauseTokensRemaining = pauseTokensRemaining;
            return this;
        }
public Streak.StreakBuilder lastActivityDate(final LocalDate lastActivityDate) {
            this.lastActivityDate = lastActivityDate;
            return this;
        }
public Streak.StreakBuilder pauseResetMonth(final Integer pauseResetMonth) {
            this.pauseResetMonth = pauseResetMonth;
            return this;
        }
public Streak.StreakBuilder pauseResetYear(final Integer pauseResetYear) {
            this.pauseResetYear = pauseResetYear;
            return this;
        }
public Streak build() {
            return new Streak(this.id, this.user, this.streakCount, this.pauseTokensRemaining, this.lastActivityDate, this.pauseResetMonth, this.pauseResetYear);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "Streak.StreakBuilder(id=" + this.id + ", user=" + this.user + ", streakCount=" + this.streakCount + ", pauseTokensRemaining=" + this.pauseTokensRemaining + ", lastActivityDate=" + this.lastActivityDate + ", pauseResetMonth=" + this.pauseResetMonth + ", pauseResetYear=" + this.pauseResetYear + ")";
        }
    }
public static Streak.StreakBuilder builder() {
        return new Streak.StreakBuilder();
    }
public Long getId() {
        return this.id;
    }
public User getUser() {
        return this.user;
    }
public Integer getStreakCount() {
        return this.streakCount;
    }
public Integer getPauseTokensRemaining() {
        return this.pauseTokensRemaining;
    }
public LocalDate getLastActivityDate() {
        return this.lastActivityDate;
    }
public Integer getPauseResetMonth() {
        return this.pauseResetMonth;
    }
public Integer getPauseResetYear() {
        return this.pauseResetYear;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setUser(final User user) {
        this.user = user;
    }
public void setStreakCount(final Integer streakCount) {
        this.streakCount = streakCount;
    }
public void setPauseTokensRemaining(final Integer pauseTokensRemaining) {
        this.pauseTokensRemaining = pauseTokensRemaining;
    }
public void setLastActivityDate(final LocalDate lastActivityDate) {
        this.lastActivityDate = lastActivityDate;
    }
public void setPauseResetMonth(final Integer pauseResetMonth) {
        this.pauseResetMonth = pauseResetMonth;
    }
public void setPauseResetYear(final Integer pauseResetYear) {
        this.pauseResetYear = pauseResetYear;
    }
public Streak() {
    }
public Streak(final Long id, final User user, final Integer streakCount, final Integer pauseTokensRemaining, final LocalDate lastActivityDate, final Integer pauseResetMonth, final Integer pauseResetYear) {
        this.id = id;
        this.user = user;
        this.streakCount = streakCount;
        this.pauseTokensRemaining = pauseTokensRemaining;
        this.lastActivityDate = lastActivityDate;
        this.pauseResetMonth = pauseResetMonth;
        this.pauseResetYear = pauseResetYear;
    }
}
