// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.entity;

import com.fitconnect.entity.enums.BookingStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDate;

@Entity
@Table(name = "trainer_bookings")
public class TrainerBooking {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trainer_id", nullable = false)
    private Trainer trainer;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @Column(nullable = false)
    private LocalDate date;
    @Column(nullable = false)
    private String timeSlot;
    @Column
    private Integer userRating;
    @Column(length = 1000)
    private String userReview;
    @Column(length = 1000)
    private String trainerResponseMessage;
    @Column
    private String trainerProposedTimeSlot;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private BookingStatus status;
public static class TrainerBookingBuilder {
private Long id;
private Trainer trainer;
private User user;
private LocalDate date;
private String timeSlot;
private Integer userRating;
private String userReview;
private String trainerResponseMessage;
private String trainerProposedTimeSlot;
private BookingStatus status;
TrainerBookingBuilder() {
        }
public TrainerBooking.TrainerBookingBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public TrainerBooking.TrainerBookingBuilder trainer(final Trainer trainer) {
            this.trainer = trainer;
            return this;
        }
public TrainerBooking.TrainerBookingBuilder user(final User user) {
            this.user = user;
            return this;
        }
public TrainerBooking.TrainerBookingBuilder date(final LocalDate date) {
            this.date = date;
            return this;
        }
public TrainerBooking.TrainerBookingBuilder timeSlot(final String timeSlot) {
            this.timeSlot = timeSlot;
            return this;
        }
public TrainerBooking.TrainerBookingBuilder userRating(final Integer userRating) {
            this.userRating = userRating;
            return this;
        }
public TrainerBooking.TrainerBookingBuilder userReview(final String userReview) {
            this.userReview = userReview;
            return this;
        }
public TrainerBooking.TrainerBookingBuilder trainerResponseMessage(final String trainerResponseMessage) {
            this.trainerResponseMessage = trainerResponseMessage;
            return this;
        }
public TrainerBooking.TrainerBookingBuilder trainerProposedTimeSlot(final String trainerProposedTimeSlot) {
            this.trainerProposedTimeSlot = trainerProposedTimeSlot;
            return this;
        }
public TrainerBooking.TrainerBookingBuilder status(final BookingStatus status) {
            this.status = status;
            return this;
        }
public TrainerBooking build() {
            return new TrainerBooking(this.id, this.trainer, this.user, this.date, this.timeSlot, this.userRating, this.userReview, this.trainerResponseMessage, this.trainerProposedTimeSlot, this.status);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "TrainerBooking.TrainerBookingBuilder(id=" + this.id + ", trainer=" + this.trainer + ", user=" + this.user + ", date=" + this.date + ", timeSlot=" + this.timeSlot + ", userRating=" + this.userRating + ", userReview=" + this.userReview + ", trainerResponseMessage=" + this.trainerResponseMessage + ", trainerProposedTimeSlot=" + this.trainerProposedTimeSlot + ", status=" + this.status + ")";
        }
    }
public static TrainerBooking.TrainerBookingBuilder builder() {
        return new TrainerBooking.TrainerBookingBuilder();
    }
public Long getId() {
        return this.id;
    }
public Trainer getTrainer() {
        return this.trainer;
    }
public User getUser() {
        return this.user;
    }
public LocalDate getDate() {
        return this.date;
    }
public String getTimeSlot() {
        return this.timeSlot;
    }
public Integer getUserRating() {
        return this.userRating;
    }
public String getUserReview() {
        return this.userReview;
    }
public String getTrainerResponseMessage() {
        return this.trainerResponseMessage;
    }
public String getTrainerProposedTimeSlot() {
        return this.trainerProposedTimeSlot;
    }
public BookingStatus getStatus() {
        return this.status;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setTrainer(final Trainer trainer) {
        this.trainer = trainer;
    }
public void setUser(final User user) {
        this.user = user;
    }
public void setDate(final LocalDate date) {
        this.date = date;
    }
public void setTimeSlot(final String timeSlot) {
        this.timeSlot = timeSlot;
    }
public void setUserRating(final Integer userRating) {
        this.userRating = userRating;
    }
public void setUserReview(final String userReview) {
        this.userReview = userReview;
    }
public void setTrainerResponseMessage(final String trainerResponseMessage) {
        this.trainerResponseMessage = trainerResponseMessage;
    }
public void setTrainerProposedTimeSlot(final String trainerProposedTimeSlot) {
        this.trainerProposedTimeSlot = trainerProposedTimeSlot;
    }
public void setStatus(final BookingStatus status) {
        this.status = status;
    }
public TrainerBooking() {
    }
public TrainerBooking(final Long id, final Trainer trainer, final User user, final LocalDate date, final String timeSlot, final Integer userRating, final String userReview, final String trainerResponseMessage, final String trainerProposedTimeSlot, final BookingStatus status) {
        this.id = id;
        this.trainer = trainer;
        this.user = user;
        this.date = date;
        this.timeSlot = timeSlot;
        this.userRating = userRating;
        this.userReview = userReview;
        this.trainerResponseMessage = trainerResponseMessage;
        this.trainerProposedTimeSlot = trainerProposedTimeSlot;
        this.status = status;
    }
}
