// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

@Entity
@Table(name = "trainers")
public class Trainer {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gym_id", nullable = false)
    private Gym gym;
    @Column(nullable = false)
    private Integer experience;
    @Column(nullable = false)
    private String specialization;
    @Column(nullable = false)
    private Double rating;
public static class TrainerBuilder {
private Long id;
private User user;
private Gym gym;
private Integer experience;
private String specialization;
private Double rating;
TrainerBuilder() {
        }
public Trainer.TrainerBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public Trainer.TrainerBuilder user(final User user) {
            this.user = user;
            return this;
        }
public Trainer.TrainerBuilder gym(final Gym gym) {
            this.gym = gym;
            return this;
        }
public Trainer.TrainerBuilder experience(final Integer experience) {
            this.experience = experience;
            return this;
        }
public Trainer.TrainerBuilder specialization(final String specialization) {
            this.specialization = specialization;
            return this;
        }
public Trainer.TrainerBuilder rating(final Double rating) {
            this.rating = rating;
            return this;
        }
public Trainer build() {
            return new Trainer(this.id, this.user, this.gym, this.experience, this.specialization, this.rating);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "Trainer.TrainerBuilder(id=" + this.id + ", user=" + this.user + ", gym=" + this.gym + ", experience=" + this.experience + ", specialization=" + this.specialization + ", rating=" + this.rating + ")";
        }
    }
public static Trainer.TrainerBuilder builder() {
        return new Trainer.TrainerBuilder();
    }
public Long getId() {
        return this.id;
    }
public User getUser() {
        return this.user;
    }
public Gym getGym() {
        return this.gym;
    }
public Integer getExperience() {
        return this.experience;
    }
public String getSpecialization() {
        return this.specialization;
    }
public Double getRating() {
        return this.rating;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setUser(final User user) {
        this.user = user;
    }
public void setGym(final Gym gym) {
        this.gym = gym;
    }
public void setExperience(final Integer experience) {
        this.experience = experience;
    }
public void setSpecialization(final String specialization) {
        this.specialization = specialization;
    }
public void setRating(final Double rating) {
        this.rating = rating;
    }
public Trainer() {
    }
public Trainer(final Long id, final User user, final Gym gym, final Integer experience, final String specialization, final Double rating) {
        this.id = id;
        this.user = user;
        this.gym = gym;
        this.experience = experience;
        this.specialization = specialization;
        this.rating = rating;
    }
}
