// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.entity;

import com.fitconnect.entity.enums.Role;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

@Entity
@Table(name = "users")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String name;
    @Column(nullable = false, unique = true)
    private String email;
    @Column(nullable = false)
    private String password;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }
public static class UserBuilder {
private Long id;
private String name;
private String email;
private String password;
private Role role;
private LocalDateTime createdAt;
UserBuilder() {
        }
public User.UserBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public User.UserBuilder name(final String name) {
            this.name = name;
            return this;
        }
public User.UserBuilder email(final String email) {
            this.email = email;
            return this;
        }
public User.UserBuilder password(final String password) {
            this.password = password;
            return this;
        }
public User.UserBuilder role(final Role role) {
            this.role = role;
            return this;
        }
public User.UserBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }
public User build() {
            return new User(this.id, this.name, this.email, this.password, this.role, this.createdAt);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "User.UserBuilder(id=" + this.id + ", name=" + this.name + ", email=" + this.email + ", password=" + this.password + ", role=" + this.role + ", createdAt=" + this.createdAt + ")";
        }
    }
public static User.UserBuilder builder() {
        return new User.UserBuilder();
    }
public Long getId() {
        return this.id;
    }
public String getName() {
        return this.name;
    }
public String getEmail() {
        return this.email;
    }
public String getPassword() {
        return this.password;
    }
public Role getRole() {
        return this.role;
    }
public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setName(final String name) {
        this.name = name;
    }
public void setEmail(final String email) {
        this.email = email;
    }
public void setPassword(final String password) {
        this.password = password;
    }
public void setRole(final Role role) {
        this.role = role;
    }
public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
public User() {
    }
public User(final Long id, final String name, final String email, final String password, final Role role, final LocalDateTime createdAt) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role;
        this.createdAt = createdAt;
    }
}
