// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "workouts")
public class Workout {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @Column(nullable = false)
    private String exerciseName;
    @Column(nullable = false)
    private BigDecimal weight;
    @Column(nullable = false)
    private Integer reps;
    @Column(nullable = false)
    private Integer duration;
    @Column(nullable = false)
    private BigDecimal caloriesBurned;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }
public static class WorkoutBuilder {
private Long id;
private User user;
private String exerciseName;
private BigDecimal weight;
private Integer reps;
private Integer duration;
private BigDecimal caloriesBurned;
private LocalDateTime createdAt;
WorkoutBuilder() {
        }
public Workout.WorkoutBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public Workout.WorkoutBuilder user(final User user) {
            this.user = user;
            return this;
        }
public Workout.WorkoutBuilder exerciseName(final String exerciseName) {
            this.exerciseName = exerciseName;
            return this;
        }
public Workout.WorkoutBuilder weight(final BigDecimal weight) {
            this.weight = weight;
            return this;
        }
public Workout.WorkoutBuilder reps(final Integer reps) {
            this.reps = reps;
            return this;
        }
public Workout.WorkoutBuilder duration(final Integer duration) {
            this.duration = duration;
            return this;
        }
public Workout.WorkoutBuilder caloriesBurned(final BigDecimal caloriesBurned) {
            this.caloriesBurned = caloriesBurned;
            return this;
        }
public Workout.WorkoutBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }
public Workout build() {
            return new Workout(this.id, this.user, this.exerciseName, this.weight, this.reps, this.duration, this.caloriesBurned, this.createdAt);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "Workout.WorkoutBuilder(id=" + this.id + ", user=" + this.user + ", exerciseName=" + this.exerciseName + ", weight=" + this.weight + ", reps=" + this.reps + ", duration=" + this.duration + ", caloriesBurned=" + this.caloriesBurned + ", createdAt=" + this.createdAt + ")";
        }
    }
public static Workout.WorkoutBuilder builder() {
        return new Workout.WorkoutBuilder();
    }
public Long getId() {
        return this.id;
    }
public User getUser() {
        return this.user;
    }
public String getExerciseName() {
        return this.exerciseName;
    }
public BigDecimal getWeight() {
        return this.weight;
    }
public Integer getReps() {
        return this.reps;
    }
public Integer getDuration() {
        return this.duration;
    }
public BigDecimal getCaloriesBurned() {
        return this.caloriesBurned;
    }
public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setUser(final User user) {
        this.user = user;
    }
public void setExerciseName(final String exerciseName) {
        this.exerciseName = exerciseName;
    }
public void setWeight(final BigDecimal weight) {
        this.weight = weight;
    }
public void setReps(final Integer reps) {
        this.reps = reps;
    }
public void setDuration(final Integer duration) {
        this.duration = duration;
    }
public void setCaloriesBurned(final BigDecimal caloriesBurned) {
        this.caloriesBurned = caloriesBurned;
    }
public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
public Workout() {
    }
public Workout(final Long id, final User user, final String exerciseName, final BigDecimal weight, final Integer reps, final Integer duration, final BigDecimal caloriesBurned, final LocalDateTime createdAt) {
        this.id = id;
        this.user = user;
        this.exerciseName = exerciseName;
        this.weight = weight;
        this.reps = reps;
        this.duration = duration;
        this.caloriesBurned = caloriesBurned;
        this.createdAt = createdAt;
    }
}
