// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import java.time.LocalDateTime;

public class AttendanceResponse {
    private Long id;
    private Long userId;
    private Long gymId;
    private LocalDateTime checkInTime;
AttendanceResponse(final Long id, final Long userId, final Long gymId, final LocalDateTime checkInTime) {
        this.id = id;
        this.userId = userId;
        this.gymId = gymId;
        this.checkInTime = checkInTime;
    }
public static class AttendanceResponseBuilder {
private Long id;
private Long userId;
private Long gymId;
private LocalDateTime checkInTime;
AttendanceResponseBuilder() {
        }
public AttendanceResponse.AttendanceResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public AttendanceResponse.AttendanceResponseBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }
public AttendanceResponse.AttendanceResponseBuilder gymId(final Long gymId) {
            this.gymId = gymId;
            return this;
        }
public AttendanceResponse.AttendanceResponseBuilder checkInTime(final LocalDateTime checkInTime) {
            this.checkInTime = checkInTime;
            return this;
        }
public AttendanceResponse build() {
            return new AttendanceResponse(this.id, this.userId, this.gymId, this.checkInTime);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "AttendanceResponse.AttendanceResponseBuilder(id=" + this.id + ", userId=" + this.userId + ", gymId=" + this.gymId + ", checkInTime=" + this.checkInTime + ")";
        }
    }
public static AttendanceResponse.AttendanceResponseBuilder builder() {
        return new AttendanceResponse.AttendanceResponseBuilder();
    }
public Long getId() {
        return this.id;
    }
public Long getUserId() {
        return this.userId;
    }
public Long getGymId() {
        return this.gymId;
    }
public LocalDateTime getCheckInTime() {
        return this.checkInTime;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setUserId(final Long userId) {
        this.userId = userId;
    }
public void setGymId(final Long gymId) {
        this.gymId = gymId;
    }
public void setCheckInTime(final LocalDateTime checkInTime) {
        this.checkInTime = checkInTime;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AttendanceResponse)) return false;
        final AttendanceResponse other = (AttendanceResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$gymId = this.getGymId();
        final java.lang.Object other$gymId = other.getGymId();
        if (this$gymId == null ? other$gymId != null : !this$gymId.equals(other$gymId)) return false;
        final java.lang.Object this$checkInTime = this.getCheckInTime();
        final java.lang.Object other$checkInTime = other.getCheckInTime();
        if (this$checkInTime == null ? other$checkInTime != null : !this$checkInTime.equals(other$checkInTime)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AttendanceResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $gymId = this.getGymId();
        result = result * PRIME + ($gymId == null ? 43 : $gymId.hashCode());
        final java.lang.Object $checkInTime = this.getCheckInTime();
        result = result * PRIME + ($checkInTime == null ? 43 : $checkInTime.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "AttendanceResponse(id=" + this.getId() + ", userId=" + this.getUserId() + ", gymId=" + this.getGymId() + ", checkInTime=" + this.getCheckInTime() + ")";
    }
}
