// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

public class AttendanceCheckInRequest {
    private Long gymId;
public AttendanceCheckInRequest() {
    }
public Long getGymId() {
        return this.gymId;
    }
public void setGymId(final Long gymId) {
        this.gymId = gymId;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AttendanceCheckInRequest)) return false;
        final AttendanceCheckInRequest other = (AttendanceCheckInRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$gymId = this.getGymId();
        final java.lang.Object other$gymId = other.getGymId();
        if (this$gymId == null ? other$gymId != null : !this$gymId.equals(other$gymId)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AttendanceCheckInRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $gymId = this.getGymId();
        result = result * PRIME + ($gymId == null ? 43 : $gymId.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "AttendanceCheckInRequest(gymId=" + this.getGymId() + ")";
    }
}
