// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import com.fitconnect.entity.enums.Role;

public class AuthResponse {
    private String token;
    private Long userId;
    private String name;
    private String email;
    private Role role;

    public static AuthResponseBuilder builder() {
        return new AuthResponseBuilder();
    }


    public static class AuthResponseBuilder {
        private String token;
        private Long userId;
        private String name;
        private String email;
        private Role role;

        AuthResponseBuilder() {
        }

        public AuthResponseBuilder token(String token) {
            this.token = token;
            return this;
        }

        public AuthResponseBuilder userId(Long userId) {
            this.userId = userId;
            return this;
        }

        public AuthResponseBuilder name(String name) {
            this.name = name;
            return this;
        }

        public AuthResponseBuilder email(String email) {
            this.email = email;
            return this;
        }

        public AuthResponseBuilder role(Role role) {
            this.role = role;
            return this;
        }

        public AuthResponse build() {
            return new AuthResponse(this.token, this.userId, this.name, this.email, this.role);
        }

        public String toString() {
            return "AuthResponse.AuthResponseBuilder(token=" + this.token + ", userId=" + this.userId + ", name=" + this.name + ", email=" + this.email + ", role=" + this.role + ")";
        }
    }
public String getToken() {
        return this.token;
    }
public Long getUserId() {
        return this.userId;
    }
public String getName() {
        return this.name;
    }
public String getEmail() {
        return this.email;
    }
public Role getRole() {
        return this.role;
    }
public void setToken(final String token) {
        this.token = token;
    }
public void setUserId(final Long userId) {
        this.userId = userId;
    }
public void setName(final String name) {
        this.name = name;
    }
public void setEmail(final String email) {
        this.email = email;
    }
public void setRole(final Role role) {
        this.role = role;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AuthResponse)) return false;
        final AuthResponse other = (AuthResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$token = this.getToken();
        final java.lang.Object other$token = other.getToken();
        if (this$token == null ? other$token != null : !this$token.equals(other$token)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AuthResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $token = this.getToken();
        result = result * PRIME + ($token == null ? 43 : $token.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "AuthResponse(token=" + this.getToken() + ", userId=" + this.getUserId() + ", name=" + this.getName() + ", email=" + this.getEmail() + ", role=" + this.getRole() + ")";
    }
public AuthResponse() {
    }
public AuthResponse(final String token, final Long userId, final String name, final String email, final Role role) {
        this.token = token;
        this.userId = userId;
        this.name = name;
        this.email = email;
        this.role = role;
    }
}
