// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;

public class BookingRequest {
    @NotNull
    private Long trainerId;
    @NotNull
    private LocalDate date;
    @NotBlank
    private String timeSlot;
public BookingRequest() {
    }
public Long getTrainerId() {
        return this.trainerId;
    }
public LocalDate getDate() {
        return this.date;
    }
public String getTimeSlot() {
        return this.timeSlot;
    }
public void setTrainerId(final Long trainerId) {
        this.trainerId = trainerId;
    }
public void setDate(final LocalDate date) {
        this.date = date;
    }
public void setTimeSlot(final String timeSlot) {
        this.timeSlot = timeSlot;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BookingRequest)) return false;
        final BookingRequest other = (BookingRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$trainerId = this.getTrainerId();
        final java.lang.Object other$trainerId = other.getTrainerId();
        if (this$trainerId == null ? other$trainerId != null : !this$trainerId.equals(other$trainerId)) return false;
        final java.lang.Object this$date = this.getDate();
        final java.lang.Object other$date = other.getDate();
        if (this$date == null ? other$date != null : !this$date.equals(other$date)) return false;
        final java.lang.Object this$timeSlot = this.getTimeSlot();
        final java.lang.Object other$timeSlot = other.getTimeSlot();
        if (this$timeSlot == null ? other$timeSlot != null : !this$timeSlot.equals(other$timeSlot)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BookingRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $trainerId = this.getTrainerId();
        result = result * PRIME + ($trainerId == null ? 43 : $trainerId.hashCode());
        final java.lang.Object $date = this.getDate();
        result = result * PRIME + ($date == null ? 43 : $date.hashCode());
        final java.lang.Object $timeSlot = this.getTimeSlot();
        result = result * PRIME + ($timeSlot == null ? 43 : $timeSlot.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "BookingRequest(trainerId=" + this.getTrainerId() + ", date=" + this.getDate() + ", timeSlot=" + this.getTimeSlot() + ")";
    }
}
