// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import jakarta.validation.constraints.NotBlank;

public class BookingStatusUpdateRequest {
    @NotBlank
    private String action;
    private String message;
    private String proposedTimeSlot;
public BookingStatusUpdateRequest() {
    }
public String getAction() {
        return this.action;
    }
public String getMessage() {
        return this.message;
    }
public String getProposedTimeSlot() {
        return this.proposedTimeSlot;
    }
public void setAction(final String action) {
        this.action = action;
    }
public void setMessage(final String message) {
        this.message = message;
    }
public void setProposedTimeSlot(final String proposedTimeSlot) {
        this.proposedTimeSlot = proposedTimeSlot;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BookingStatusUpdateRequest)) return false;
        final BookingStatusUpdateRequest other = (BookingStatusUpdateRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$action = this.getAction();
        final java.lang.Object other$action = other.getAction();
        if (this$action == null ? other$action != null : !this$action.equals(other$action)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        final java.lang.Object this$proposedTimeSlot = this.getProposedTimeSlot();
        final java.lang.Object other$proposedTimeSlot = other.getProposedTimeSlot();
        if (this$proposedTimeSlot == null ? other$proposedTimeSlot != null : !this$proposedTimeSlot.equals(other$proposedTimeSlot)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BookingStatusUpdateRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $action = this.getAction();
        result = result * PRIME + ($action == null ? 43 : $action.hashCode());
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        final java.lang.Object $proposedTimeSlot = this.getProposedTimeSlot();
        result = result * PRIME + ($proposedTimeSlot == null ? 43 : $proposedTimeSlot.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "BookingStatusUpdateRequest(action=" + this.getAction() + ", message=" + this.getMessage() + ", proposedTimeSlot=" + this.getProposedTimeSlot() + ")";
    }
}
