// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import com.fitconnect.entity.TrainerBooking;
import com.fitconnect.entity.enums.BookingStatus;
import java.time.LocalDate;

/**
 * DTO for trainer booking responses.
 *
 * ===== BUILDER PATTERN =====
 * Lombok @Builder generates a fluent builder at compile time.
 * Instead of a telescoping constructor like:
 *   new BookingResponse(id, trainerId, userId, trainerName, ...)   ← hard to read
 *
 * We use:
 *   BookingResponse response = BookingResponse.builder()
 *       .id(booking.getId())
 *       .trainerId(booking.getTrainer().getId())
 *       .userId(booking.getUser().getId())
 *       .trainerName(booking.getTrainer().getUser().getName())
 *       .userName(booking.getUser().getName())
 *       .date(booking.getDate())
 *       .timeSlot(booking.getTimeSlot())
 *       .status(booking.getStatus())
 *       .build();                                                   ← clean & readable
 *
 * @see BookingService#toResponse(TrainerBooking) — live usage in the service layer
 * ==========================
 */
public class BookingResponse {
    private Long id;
    private Long trainerId;
    private Long userId;
    private String trainerName;
    private String userName;
    private LocalDate date;
    private String timeSlot;
    private Integer userRating;
    private String userReview;
    private String trainerResponseMessage;
    private String trainerProposedTimeSlot;
    private BookingStatus status;

    /**
     * Builder Pattern — static factory method.
     *
     * Converts a {@link TrainerBooking} entity into a {@link BookingResponse} DTO
     * using the Lombok-generated builder. This is the canonical way to construct
     * this DTO, keeping object creation logic in one place.
     *
     * Usage:
     *   BookingResponse dto = BookingResponse.from(booking);
     */
    public static BookingResponse from(TrainerBooking booking) {
        return  // 1. Get builder instance
        // 2. Set each field fluently
        BookingResponse.builder().id(booking.getId()).trainerId(booking.getTrainer().getId()).userId(booking.getUser().getId()).trainerName(booking.getTrainer().getUser().getName()).userName(booking.getUser().getName()).date(booking.getDate()).timeSlot(booking.getTimeSlot()).userRating(booking.getUserRating()).userReview(booking.getUserReview()).trainerResponseMessage(booking.getTrainerResponseMessage()).trainerProposedTimeSlot(booking.getTrainerProposedTimeSlot()).status(booking.getStatus()).build(); // 3. Construct the immutable object
    }
BookingResponse(final Long id, final Long trainerId, final Long userId, final String trainerName, final String userName, final LocalDate date, final String timeSlot, final Integer userRating, final String userReview, final String trainerResponseMessage, final String trainerProposedTimeSlot, final BookingStatus status) {
        this.id = id;
        this.trainerId = trainerId;
        this.userId = userId;
        this.trainerName = trainerName;
        this.userName = userName;
        this.date = date;
        this.timeSlot = timeSlot;
        this.userRating = userRating;
        this.userReview = userReview;
        this.trainerResponseMessage = trainerResponseMessage;
        this.trainerProposedTimeSlot = trainerProposedTimeSlot;
        this.status = status;
    }
public static class BookingResponseBuilder {
private Long id;
private Long trainerId;
private Long userId;
private String trainerName;
private String userName;
private LocalDate date;
private String timeSlot;
private Integer userRating;
private String userReview;
private String trainerResponseMessage;
private String trainerProposedTimeSlot;
private BookingStatus status;
BookingResponseBuilder() {
        }
public BookingResponse.BookingResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public BookingResponse.BookingResponseBuilder trainerId(final Long trainerId) {
            this.trainerId = trainerId;
            return this;
        }
public BookingResponse.BookingResponseBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }
public BookingResponse.BookingResponseBuilder trainerName(final String trainerName) {
            this.trainerName = trainerName;
            return this;
        }
public BookingResponse.BookingResponseBuilder userName(final String userName) {
            this.userName = userName;
            return this;
        }
public BookingResponse.BookingResponseBuilder date(final LocalDate date) {
            this.date = date;
            return this;
        }
public BookingResponse.BookingResponseBuilder timeSlot(final String timeSlot) {
            this.timeSlot = timeSlot;
            return this;
        }
public BookingResponse.BookingResponseBuilder userRating(final Integer userRating) {
            this.userRating = userRating;
            return this;
        }
public BookingResponse.BookingResponseBuilder userReview(final String userReview) {
            this.userReview = userReview;
            return this;
        }
public BookingResponse.BookingResponseBuilder trainerResponseMessage(final String trainerResponseMessage) {
            this.trainerResponseMessage = trainerResponseMessage;
            return this;
        }
public BookingResponse.BookingResponseBuilder trainerProposedTimeSlot(final String trainerProposedTimeSlot) {
            this.trainerProposedTimeSlot = trainerProposedTimeSlot;
            return this;
        }
public BookingResponse.BookingResponseBuilder status(final BookingStatus status) {
            this.status = status;
            return this;
        }
public BookingResponse build() {
            return new BookingResponse(this.id, this.trainerId, this.userId, this.trainerName, this.userName, this.date, this.timeSlot, this.userRating, this.userReview, this.trainerResponseMessage, this.trainerProposedTimeSlot, this.status);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "BookingResponse.BookingResponseBuilder(id=" + this.id + ", trainerId=" + this.trainerId + ", userId=" + this.userId + ", trainerName=" + this.trainerName + ", userName=" + this.userName + ", date=" + this.date + ", timeSlot=" + this.timeSlot + ", userRating=" + this.userRating + ", userReview=" + this.userReview + ", trainerResponseMessage=" + this.trainerResponseMessage + ", trainerProposedTimeSlot=" + this.trainerProposedTimeSlot + ", status=" + this.status + ")";
        }
    }
public static BookingResponse.BookingResponseBuilder builder() {
        return new BookingResponse.BookingResponseBuilder();
    }
public Long getId() {
        return this.id;
    }
public Long getTrainerId() {
        return this.trainerId;
    }
public Long getUserId() {
        return this.userId;
    }
public String getTrainerName() {
        return this.trainerName;
    }
public String getUserName() {
        return this.userName;
    }
public LocalDate getDate() {
        return this.date;
    }
public String getTimeSlot() {
        return this.timeSlot;
    }
public Integer getUserRating() {
        return this.userRating;
    }
public String getUserReview() {
        return this.userReview;
    }
public String getTrainerResponseMessage() {
        return this.trainerResponseMessage;
    }
public String getTrainerProposedTimeSlot() {
        return this.trainerProposedTimeSlot;
    }
public BookingStatus getStatus() {
        return this.status;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setTrainerId(final Long trainerId) {
        this.trainerId = trainerId;
    }
public void setUserId(final Long userId) {
        this.userId = userId;
    }
public void setTrainerName(final String trainerName) {
        this.trainerName = trainerName;
    }
public void setUserName(final String userName) {
        this.userName = userName;
    }
public void setDate(final LocalDate date) {
        this.date = date;
    }
public void setTimeSlot(final String timeSlot) {
        this.timeSlot = timeSlot;
    }
public void setUserRating(final Integer userRating) {
        this.userRating = userRating;
    }
public void setUserReview(final String userReview) {
        this.userReview = userReview;
    }
public void setTrainerResponseMessage(final String trainerResponseMessage) {
        this.trainerResponseMessage = trainerResponseMessage;
    }
public void setTrainerProposedTimeSlot(final String trainerProposedTimeSlot) {
        this.trainerProposedTimeSlot = trainerProposedTimeSlot;
    }
public void setStatus(final BookingStatus status) {
        this.status = status;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BookingResponse)) return false;
        final BookingResponse other = (BookingResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$trainerId = this.getTrainerId();
        final java.lang.Object other$trainerId = other.getTrainerId();
        if (this$trainerId == null ? other$trainerId != null : !this$trainerId.equals(other$trainerId)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$userRating = this.getUserRating();
        final java.lang.Object other$userRating = other.getUserRating();
        if (this$userRating == null ? other$userRating != null : !this$userRating.equals(other$userRating)) return false;
        final java.lang.Object this$trainerName = this.getTrainerName();
        final java.lang.Object other$trainerName = other.getTrainerName();
        if (this$trainerName == null ? other$trainerName != null : !this$trainerName.equals(other$trainerName)) return false;
        final java.lang.Object this$userName = this.getUserName();
        final java.lang.Object other$userName = other.getUserName();
        if (this$userName == null ? other$userName != null : !this$userName.equals(other$userName)) return false;
        final java.lang.Object this$date = this.getDate();
        final java.lang.Object other$date = other.getDate();
        if (this$date == null ? other$date != null : !this$date.equals(other$date)) return false;
        final java.lang.Object this$timeSlot = this.getTimeSlot();
        final java.lang.Object other$timeSlot = other.getTimeSlot();
        if (this$timeSlot == null ? other$timeSlot != null : !this$timeSlot.equals(other$timeSlot)) return false;
        final java.lang.Object this$userReview = this.getUserReview();
        final java.lang.Object other$userReview = other.getUserReview();
        if (this$userReview == null ? other$userReview != null : !this$userReview.equals(other$userReview)) return false;
        final java.lang.Object this$trainerResponseMessage = this.getTrainerResponseMessage();
        final java.lang.Object other$trainerResponseMessage = other.getTrainerResponseMessage();
        if (this$trainerResponseMessage == null ? other$trainerResponseMessage != null : !this$trainerResponseMessage.equals(other$trainerResponseMessage)) return false;
        final java.lang.Object this$trainerProposedTimeSlot = this.getTrainerProposedTimeSlot();
        final java.lang.Object other$trainerProposedTimeSlot = other.getTrainerProposedTimeSlot();
        if (this$trainerProposedTimeSlot == null ? other$trainerProposedTimeSlot != null : !this$trainerProposedTimeSlot.equals(other$trainerProposedTimeSlot)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BookingResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $trainerId = this.getTrainerId();
        result = result * PRIME + ($trainerId == null ? 43 : $trainerId.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $userRating = this.getUserRating();
        result = result * PRIME + ($userRating == null ? 43 : $userRating.hashCode());
        final java.lang.Object $trainerName = this.getTrainerName();
        result = result * PRIME + ($trainerName == null ? 43 : $trainerName.hashCode());
        final java.lang.Object $userName = this.getUserName();
        result = result * PRIME + ($userName == null ? 43 : $userName.hashCode());
        final java.lang.Object $date = this.getDate();
        result = result * PRIME + ($date == null ? 43 : $date.hashCode());
        final java.lang.Object $timeSlot = this.getTimeSlot();
        result = result * PRIME + ($timeSlot == null ? 43 : $timeSlot.hashCode());
        final java.lang.Object $userReview = this.getUserReview();
        result = result * PRIME + ($userReview == null ? 43 : $userReview.hashCode());
        final java.lang.Object $trainerResponseMessage = this.getTrainerResponseMessage();
        result = result * PRIME + ($trainerResponseMessage == null ? 43 : $trainerResponseMessage.hashCode());
        final java.lang.Object $trainerProposedTimeSlot = this.getTrainerProposedTimeSlot();
        result = result * PRIME + ($trainerProposedTimeSlot == null ? 43 : $trainerProposedTimeSlot.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "BookingResponse(id=" + this.getId() + ", trainerId=" + this.getTrainerId() + ", userId=" + this.getUserId() + ", trainerName=" + this.getTrainerName() + ", userName=" + this.getUserName() + ", date=" + this.getDate() + ", timeSlot=" + this.getTimeSlot() + ", userRating=" + this.getUserRating() + ", userReview=" + this.getUserReview() + ", trainerResponseMessage=" + this.getTrainerResponseMessage() + ", trainerProposedTimeSlot=" + this.getTrainerProposedTimeSlot() + ", status=" + this.getStatus() + ")";
    }
}
