// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;

public class BookingRatingRequest {
    @Min(1)
    @Max(5)
    private Integer rating;
    @NotBlank
    private String review;
public BookingRatingRequest() {
    }
public Integer getRating() {
        return this.rating;
    }
public String getReview() {
        return this.review;
    }
public void setRating(final Integer rating) {
        this.rating = rating;
    }
public void setReview(final String review) {
        this.review = review;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BookingRatingRequest)) return false;
        final BookingRatingRequest other = (BookingRatingRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$rating = this.getRating();
        final java.lang.Object other$rating = other.getRating();
        if (this$rating == null ? other$rating != null : !this$rating.equals(other$rating)) return false;
        final java.lang.Object this$review = this.getReview();
        final java.lang.Object other$review = other.getReview();
        if (this$review == null ? other$review != null : !this$review.equals(other$review)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BookingRatingRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $rating = this.getRating();
        result = result * PRIME + ($rating == null ? 43 : $rating.hashCode());
        final java.lang.Object $review = this.getReview();
        result = result * PRIME + ($review == null ? 43 : $review.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "BookingRatingRequest(rating=" + this.getRating() + ", review=" + this.getReview() + ")";
    }
}
