// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;

public class EquipmentRentalListingRequest {
    @NotNull
    private Long sellerGymId;
    @NotBlank
    private String equipmentName;
    private String details;
    @NotNull
    @DecimalMin("0.01")
    private BigDecimal monthlyRentPrice;
public EquipmentRentalListingRequest() {
    }
public Long getSellerGymId() {
        return this.sellerGymId;
    }
public String getEquipmentName() {
        return this.equipmentName;
    }
public String getDetails() {
        return this.details;
    }
public BigDecimal getMonthlyRentPrice() {
        return this.monthlyRentPrice;
    }
public void setSellerGymId(final Long sellerGymId) {
        this.sellerGymId = sellerGymId;
    }
public void setEquipmentName(final String equipmentName) {
        this.equipmentName = equipmentName;
    }
public void setDetails(final String details) {
        this.details = details;
    }
public void setMonthlyRentPrice(final BigDecimal monthlyRentPrice) {
        this.monthlyRentPrice = monthlyRentPrice;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EquipmentRentalListingRequest)) return false;
        final EquipmentRentalListingRequest other = (EquipmentRentalListingRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$sellerGymId = this.getSellerGymId();
        final java.lang.Object other$sellerGymId = other.getSellerGymId();
        if (this$sellerGymId == null ? other$sellerGymId != null : !this$sellerGymId.equals(other$sellerGymId)) return false;
        final java.lang.Object this$equipmentName = this.getEquipmentName();
        final java.lang.Object other$equipmentName = other.getEquipmentName();
        if (this$equipmentName == null ? other$equipmentName != null : !this$equipmentName.equals(other$equipmentName)) return false;
        final java.lang.Object this$details = this.getDetails();
        final java.lang.Object other$details = other.getDetails();
        if (this$details == null ? other$details != null : !this$details.equals(other$details)) return false;
        final java.lang.Object this$monthlyRentPrice = this.getMonthlyRentPrice();
        final java.lang.Object other$monthlyRentPrice = other.getMonthlyRentPrice();
        if (this$monthlyRentPrice == null ? other$monthlyRentPrice != null : !this$monthlyRentPrice.equals(other$monthlyRentPrice)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EquipmentRentalListingRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $sellerGymId = this.getSellerGymId();
        result = result * PRIME + ($sellerGymId == null ? 43 : $sellerGymId.hashCode());
        final java.lang.Object $equipmentName = this.getEquipmentName();
        result = result * PRIME + ($equipmentName == null ? 43 : $equipmentName.hashCode());
        final java.lang.Object $details = this.getDetails();
        result = result * PRIME + ($details == null ? 43 : $details.hashCode());
        final java.lang.Object $monthlyRentPrice = this.getMonthlyRentPrice();
        result = result * PRIME + ($monthlyRentPrice == null ? 43 : $monthlyRentPrice.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "EquipmentRentalListingRequest(sellerGymId=" + this.getSellerGymId() + ", equipmentName=" + this.getEquipmentName() + ", details=" + this.getDetails() + ", monthlyRentPrice=" + this.getMonthlyRentPrice() + ")";
    }
}
