// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import jakarta.validation.constraints.NotNull;

public class EquipmentRentalBuyRequest {
    @NotNull
    private Long buyerGymId;
public EquipmentRentalBuyRequest() {
    }
public Long getBuyerGymId() {
        return this.buyerGymId;
    }
public void setBuyerGymId(final Long buyerGymId) {
        this.buyerGymId = buyerGymId;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EquipmentRentalBuyRequest)) return false;
        final EquipmentRentalBuyRequest other = (EquipmentRentalBuyRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$buyerGymId = this.getBuyerGymId();
        final java.lang.Object other$buyerGymId = other.getBuyerGymId();
        if (this$buyerGymId == null ? other$buyerGymId != null : !this$buyerGymId.equals(other$buyerGymId)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EquipmentRentalBuyRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $buyerGymId = this.getBuyerGymId();
        result = result * PRIME + ($buyerGymId == null ? 43 : $buyerGymId.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "EquipmentRentalBuyRequest(buyerGymId=" + this.getBuyerGymId() + ")";
    }
}
