// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import com.fitconnect.entity.enums.EquipmentCondition;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

public class EquipmentRequest {
    @NotNull
    private Long gymId;
    @NotBlank
    private String equipmentName;
    @NotNull
    @Min(1)
    private Integer quantity;
    @NotNull
    private EquipmentCondition condition;
public EquipmentRequest() {
    }
public Long getGymId() {
        return this.gymId;
    }
public String getEquipmentName() {
        return this.equipmentName;
    }
public Integer getQuantity() {
        return this.quantity;
    }
public EquipmentCondition getCondition() {
        return this.condition;
    }
public void setGymId(final Long gymId) {
        this.gymId = gymId;
    }
public void setEquipmentName(final String equipmentName) {
        this.equipmentName = equipmentName;
    }
public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }
public void setCondition(final EquipmentCondition condition) {
        this.condition = condition;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EquipmentRequest)) return false;
        final EquipmentRequest other = (EquipmentRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$gymId = this.getGymId();
        final java.lang.Object other$gymId = other.getGymId();
        if (this$gymId == null ? other$gymId != null : !this$gymId.equals(other$gymId)) return false;
        final java.lang.Object this$quantity = this.getQuantity();
        final java.lang.Object other$quantity = other.getQuantity();
        if (this$quantity == null ? other$quantity != null : !this$quantity.equals(other$quantity)) return false;
        final java.lang.Object this$equipmentName = this.getEquipmentName();
        final java.lang.Object other$equipmentName = other.getEquipmentName();
        if (this$equipmentName == null ? other$equipmentName != null : !this$equipmentName.equals(other$equipmentName)) return false;
        final java.lang.Object this$condition = this.getCondition();
        final java.lang.Object other$condition = other.getCondition();
        if (this$condition == null ? other$condition != null : !this$condition.equals(other$condition)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EquipmentRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $gymId = this.getGymId();
        result = result * PRIME + ($gymId == null ? 43 : $gymId.hashCode());
        final java.lang.Object $quantity = this.getQuantity();
        result = result * PRIME + ($quantity == null ? 43 : $quantity.hashCode());
        final java.lang.Object $equipmentName = this.getEquipmentName();
        result = result * PRIME + ($equipmentName == null ? 43 : $equipmentName.hashCode());
        final java.lang.Object $condition = this.getCondition();
        result = result * PRIME + ($condition == null ? 43 : $condition.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "EquipmentRequest(gymId=" + this.getGymId() + ", equipmentName=" + this.getEquipmentName() + ", quantity=" + this.getQuantity() + ", condition=" + this.getCondition() + ")";
    }
}
