// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class EquipmentRentalListingResponse {
    private Long id;
    private Long sellerOwnerId;
    private String sellerOwnerName;
    private String sellerOwnerEmail;
    private Long sellerGymId;
    private String sellerGymName;
    private String equipmentName;
    private String details;
    private BigDecimal monthlyRentPrice;
    private LocalDateTime createdAt;
EquipmentRentalListingResponse(final Long id, final Long sellerOwnerId, final String sellerOwnerName, final String sellerOwnerEmail, final Long sellerGymId, final String sellerGymName, final String equipmentName, final String details, final BigDecimal monthlyRentPrice, final LocalDateTime createdAt) {
        this.id = id;
        this.sellerOwnerId = sellerOwnerId;
        this.sellerOwnerName = sellerOwnerName;
        this.sellerOwnerEmail = sellerOwnerEmail;
        this.sellerGymId = sellerGymId;
        this.sellerGymName = sellerGymName;
        this.equipmentName = equipmentName;
        this.details = details;
        this.monthlyRentPrice = monthlyRentPrice;
        this.createdAt = createdAt;
    }
public static class EquipmentRentalListingResponseBuilder {
private Long id;
private Long sellerOwnerId;
private String sellerOwnerName;
private String sellerOwnerEmail;
private Long sellerGymId;
private String sellerGymName;
private String equipmentName;
private String details;
private BigDecimal monthlyRentPrice;
private LocalDateTime createdAt;
EquipmentRentalListingResponseBuilder() {
        }
public EquipmentRentalListingResponse.EquipmentRentalListingResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public EquipmentRentalListingResponse.EquipmentRentalListingResponseBuilder sellerOwnerId(final Long sellerOwnerId) {
            this.sellerOwnerId = sellerOwnerId;
            return this;
        }
public EquipmentRentalListingResponse.EquipmentRentalListingResponseBuilder sellerOwnerName(final String sellerOwnerName) {
            this.sellerOwnerName = sellerOwnerName;
            return this;
        }
public EquipmentRentalListingResponse.EquipmentRentalListingResponseBuilder sellerOwnerEmail(final String sellerOwnerEmail) {
            this.sellerOwnerEmail = sellerOwnerEmail;
            return this;
        }
public EquipmentRentalListingResponse.EquipmentRentalListingResponseBuilder sellerGymId(final Long sellerGymId) {
            this.sellerGymId = sellerGymId;
            return this;
        }
public EquipmentRentalListingResponse.EquipmentRentalListingResponseBuilder sellerGymName(final String sellerGymName) {
            this.sellerGymName = sellerGymName;
            return this;
        }
public EquipmentRentalListingResponse.EquipmentRentalListingResponseBuilder equipmentName(final String equipmentName) {
            this.equipmentName = equipmentName;
            return this;
        }
public EquipmentRentalListingResponse.EquipmentRentalListingResponseBuilder details(final String details) {
            this.details = details;
            return this;
        }
public EquipmentRentalListingResponse.EquipmentRentalListingResponseBuilder monthlyRentPrice(final BigDecimal monthlyRentPrice) {
            this.monthlyRentPrice = monthlyRentPrice;
            return this;
        }
public EquipmentRentalListingResponse.EquipmentRentalListingResponseBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }
public EquipmentRentalListingResponse build() {
            return new EquipmentRentalListingResponse(this.id, this.sellerOwnerId, this.sellerOwnerName, this.sellerOwnerEmail, this.sellerGymId, this.sellerGymName, this.equipmentName, this.details, this.monthlyRentPrice, this.createdAt);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "EquipmentRentalListingResponse.EquipmentRentalListingResponseBuilder(id=" + this.id + ", sellerOwnerId=" + this.sellerOwnerId + ", sellerOwnerName=" + this.sellerOwnerName + ", sellerOwnerEmail=" + this.sellerOwnerEmail + ", sellerGymId=" + this.sellerGymId + ", sellerGymName=" + this.sellerGymName + ", equipmentName=" + this.equipmentName + ", details=" + this.details + ", monthlyRentPrice=" + this.monthlyRentPrice + ", createdAt=" + this.createdAt + ")";
        }
    }
public static EquipmentRentalListingResponse.EquipmentRentalListingResponseBuilder builder() {
        return new EquipmentRentalListingResponse.EquipmentRentalListingResponseBuilder();
    }
public Long getId() {
        return this.id;
    }
public Long getSellerOwnerId() {
        return this.sellerOwnerId;
    }
public String getSellerOwnerName() {
        return this.sellerOwnerName;
    }
public String getSellerOwnerEmail() {
        return this.sellerOwnerEmail;
    }
public Long getSellerGymId() {
        return this.sellerGymId;
    }
public String getSellerGymName() {
        return this.sellerGymName;
    }
public String getEquipmentName() {
        return this.equipmentName;
    }
public String getDetails() {
        return this.details;
    }
public BigDecimal getMonthlyRentPrice() {
        return this.monthlyRentPrice;
    }
public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setSellerOwnerId(final Long sellerOwnerId) {
        this.sellerOwnerId = sellerOwnerId;
    }
public void setSellerOwnerName(final String sellerOwnerName) {
        this.sellerOwnerName = sellerOwnerName;
    }
public void setSellerOwnerEmail(final String sellerOwnerEmail) {
        this.sellerOwnerEmail = sellerOwnerEmail;
    }
public void setSellerGymId(final Long sellerGymId) {
        this.sellerGymId = sellerGymId;
    }
public void setSellerGymName(final String sellerGymName) {
        this.sellerGymName = sellerGymName;
    }
public void setEquipmentName(final String equipmentName) {
        this.equipmentName = equipmentName;
    }
public void setDetails(final String details) {
        this.details = details;
    }
public void setMonthlyRentPrice(final BigDecimal monthlyRentPrice) {
        this.monthlyRentPrice = monthlyRentPrice;
    }
public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EquipmentRentalListingResponse)) return false;
        final EquipmentRentalListingResponse other = (EquipmentRentalListingResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$sellerOwnerId = this.getSellerOwnerId();
        final java.lang.Object other$sellerOwnerId = other.getSellerOwnerId();
        if (this$sellerOwnerId == null ? other$sellerOwnerId != null : !this$sellerOwnerId.equals(other$sellerOwnerId)) return false;
        final java.lang.Object this$sellerGymId = this.getSellerGymId();
        final java.lang.Object other$sellerGymId = other.getSellerGymId();
        if (this$sellerGymId == null ? other$sellerGymId != null : !this$sellerGymId.equals(other$sellerGymId)) return false;
        final java.lang.Object this$sellerOwnerName = this.getSellerOwnerName();
        final java.lang.Object other$sellerOwnerName = other.getSellerOwnerName();
        if (this$sellerOwnerName == null ? other$sellerOwnerName != null : !this$sellerOwnerName.equals(other$sellerOwnerName)) return false;
        final java.lang.Object this$sellerOwnerEmail = this.getSellerOwnerEmail();
        final java.lang.Object other$sellerOwnerEmail = other.getSellerOwnerEmail();
        if (this$sellerOwnerEmail == null ? other$sellerOwnerEmail != null : !this$sellerOwnerEmail.equals(other$sellerOwnerEmail)) return false;
        final java.lang.Object this$sellerGymName = this.getSellerGymName();
        final java.lang.Object other$sellerGymName = other.getSellerGymName();
        if (this$sellerGymName == null ? other$sellerGymName != null : !this$sellerGymName.equals(other$sellerGymName)) return false;
        final java.lang.Object this$equipmentName = this.getEquipmentName();
        final java.lang.Object other$equipmentName = other.getEquipmentName();
        if (this$equipmentName == null ? other$equipmentName != null : !this$equipmentName.equals(other$equipmentName)) return false;
        final java.lang.Object this$details = this.getDetails();
        final java.lang.Object other$details = other.getDetails();
        if (this$details == null ? other$details != null : !this$details.equals(other$details)) return false;
        final java.lang.Object this$monthlyRentPrice = this.getMonthlyRentPrice();
        final java.lang.Object other$monthlyRentPrice = other.getMonthlyRentPrice();
        if (this$monthlyRentPrice == null ? other$monthlyRentPrice != null : !this$monthlyRentPrice.equals(other$monthlyRentPrice)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EquipmentRentalListingResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $sellerOwnerId = this.getSellerOwnerId();
        result = result * PRIME + ($sellerOwnerId == null ? 43 : $sellerOwnerId.hashCode());
        final java.lang.Object $sellerGymId = this.getSellerGymId();
        result = result * PRIME + ($sellerGymId == null ? 43 : $sellerGymId.hashCode());
        final java.lang.Object $sellerOwnerName = this.getSellerOwnerName();
        result = result * PRIME + ($sellerOwnerName == null ? 43 : $sellerOwnerName.hashCode());
        final java.lang.Object $sellerOwnerEmail = this.getSellerOwnerEmail();
        result = result * PRIME + ($sellerOwnerEmail == null ? 43 : $sellerOwnerEmail.hashCode());
        final java.lang.Object $sellerGymName = this.getSellerGymName();
        result = result * PRIME + ($sellerGymName == null ? 43 : $sellerGymName.hashCode());
        final java.lang.Object $equipmentName = this.getEquipmentName();
        result = result * PRIME + ($equipmentName == null ? 43 : $equipmentName.hashCode());
        final java.lang.Object $details = this.getDetails();
        result = result * PRIME + ($details == null ? 43 : $details.hashCode());
        final java.lang.Object $monthlyRentPrice = this.getMonthlyRentPrice();
        result = result * PRIME + ($monthlyRentPrice == null ? 43 : $monthlyRentPrice.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "EquipmentRentalListingResponse(id=" + this.getId() + ", sellerOwnerId=" + this.getSellerOwnerId() + ", sellerOwnerName=" + this.getSellerOwnerName() + ", sellerOwnerEmail=" + this.getSellerOwnerEmail() + ", sellerGymId=" + this.getSellerGymId() + ", sellerGymName=" + this.getSellerGymName() + ", equipmentName=" + this.getEquipmentName() + ", details=" + this.getDetails() + ", monthlyRentPrice=" + this.getMonthlyRentPrice() + ", createdAt=" + this.getCreatedAt() + ")";
    }
}
