// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class EquipmentRentalTransactionResponse {
    private Long id;
    private Long sellerOwnerId;
    private String sellerOwnerName;
    private String sellerOwnerEmail;
    private Long buyerOwnerId;
    private String buyerOwnerName;
    private String buyerOwnerEmail;
    private Long sellerGymId;
    private String sellerGymName;
    private Long buyerGymId;
    private String buyerGymName;
    private String equipmentName;
    private String details;
    private BigDecimal monthlyRentPrice;
    private LocalDateTime purchasedAt;
EquipmentRentalTransactionResponse(final Long id, final Long sellerOwnerId, final String sellerOwnerName, final String sellerOwnerEmail, final Long buyerOwnerId, final String buyerOwnerName, final String buyerOwnerEmail, final Long sellerGymId, final String sellerGymName, final Long buyerGymId, final String buyerGymName, final String equipmentName, final String details, final BigDecimal monthlyRentPrice, final LocalDateTime purchasedAt) {
        this.id = id;
        this.sellerOwnerId = sellerOwnerId;
        this.sellerOwnerName = sellerOwnerName;
        this.sellerOwnerEmail = sellerOwnerEmail;
        this.buyerOwnerId = buyerOwnerId;
        this.buyerOwnerName = buyerOwnerName;
        this.buyerOwnerEmail = buyerOwnerEmail;
        this.sellerGymId = sellerGymId;
        this.sellerGymName = sellerGymName;
        this.buyerGymId = buyerGymId;
        this.buyerGymName = buyerGymName;
        this.equipmentName = equipmentName;
        this.details = details;
        this.monthlyRentPrice = monthlyRentPrice;
        this.purchasedAt = purchasedAt;
    }
public static class EquipmentRentalTransactionResponseBuilder {
private Long id;
private Long sellerOwnerId;
private String sellerOwnerName;
private String sellerOwnerEmail;
private Long buyerOwnerId;
private String buyerOwnerName;
private String buyerOwnerEmail;
private Long sellerGymId;
private String sellerGymName;
private Long buyerGymId;
private String buyerGymName;
private String equipmentName;
private String details;
private BigDecimal monthlyRentPrice;
private LocalDateTime purchasedAt;
EquipmentRentalTransactionResponseBuilder() {
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder sellerOwnerId(final Long sellerOwnerId) {
            this.sellerOwnerId = sellerOwnerId;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder sellerOwnerName(final String sellerOwnerName) {
            this.sellerOwnerName = sellerOwnerName;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder sellerOwnerEmail(final String sellerOwnerEmail) {
            this.sellerOwnerEmail = sellerOwnerEmail;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder buyerOwnerId(final Long buyerOwnerId) {
            this.buyerOwnerId = buyerOwnerId;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder buyerOwnerName(final String buyerOwnerName) {
            this.buyerOwnerName = buyerOwnerName;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder buyerOwnerEmail(final String buyerOwnerEmail) {
            this.buyerOwnerEmail = buyerOwnerEmail;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder sellerGymId(final Long sellerGymId) {
            this.sellerGymId = sellerGymId;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder sellerGymName(final String sellerGymName) {
            this.sellerGymName = sellerGymName;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder buyerGymId(final Long buyerGymId) {
            this.buyerGymId = buyerGymId;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder buyerGymName(final String buyerGymName) {
            this.buyerGymName = buyerGymName;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder equipmentName(final String equipmentName) {
            this.equipmentName = equipmentName;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder details(final String details) {
            this.details = details;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder monthlyRentPrice(final BigDecimal monthlyRentPrice) {
            this.monthlyRentPrice = monthlyRentPrice;
            return this;
        }
public EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder purchasedAt(final LocalDateTime purchasedAt) {
            this.purchasedAt = purchasedAt;
            return this;
        }
public EquipmentRentalTransactionResponse build() {
            return new EquipmentRentalTransactionResponse(this.id, this.sellerOwnerId, this.sellerOwnerName, this.sellerOwnerEmail, this.buyerOwnerId, this.buyerOwnerName, this.buyerOwnerEmail, this.sellerGymId, this.sellerGymName, this.buyerGymId, this.buyerGymName, this.equipmentName, this.details, this.monthlyRentPrice, this.purchasedAt);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder(id=" + this.id + ", sellerOwnerId=" + this.sellerOwnerId + ", sellerOwnerName=" + this.sellerOwnerName + ", sellerOwnerEmail=" + this.sellerOwnerEmail + ", buyerOwnerId=" + this.buyerOwnerId + ", buyerOwnerName=" + this.buyerOwnerName + ", buyerOwnerEmail=" + this.buyerOwnerEmail + ", sellerGymId=" + this.sellerGymId + ", sellerGymName=" + this.sellerGymName + ", buyerGymId=" + this.buyerGymId + ", buyerGymName=" + this.buyerGymName + ", equipmentName=" + this.equipmentName + ", details=" + this.details + ", monthlyRentPrice=" + this.monthlyRentPrice + ", purchasedAt=" + this.purchasedAt + ")";
        }
    }
public static EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder builder() {
        return new EquipmentRentalTransactionResponse.EquipmentRentalTransactionResponseBuilder();
    }
public Long getId() {
        return this.id;
    }
public Long getSellerOwnerId() {
        return this.sellerOwnerId;
    }
public String getSellerOwnerName() {
        return this.sellerOwnerName;
    }
public String getSellerOwnerEmail() {
        return this.sellerOwnerEmail;
    }
public Long getBuyerOwnerId() {
        return this.buyerOwnerId;
    }
public String getBuyerOwnerName() {
        return this.buyerOwnerName;
    }
public String getBuyerOwnerEmail() {
        return this.buyerOwnerEmail;
    }
public Long getSellerGymId() {
        return this.sellerGymId;
    }
public String getSellerGymName() {
        return this.sellerGymName;
    }
public Long getBuyerGymId() {
        return this.buyerGymId;
    }
public String getBuyerGymName() {
        return this.buyerGymName;
    }
public String getEquipmentName() {
        return this.equipmentName;
    }
public String getDetails() {
        return this.details;
    }
public BigDecimal getMonthlyRentPrice() {
        return this.monthlyRentPrice;
    }
public LocalDateTime getPurchasedAt() {
        return this.purchasedAt;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setSellerOwnerId(final Long sellerOwnerId) {
        this.sellerOwnerId = sellerOwnerId;
    }
public void setSellerOwnerName(final String sellerOwnerName) {
        this.sellerOwnerName = sellerOwnerName;
    }
public void setSellerOwnerEmail(final String sellerOwnerEmail) {
        this.sellerOwnerEmail = sellerOwnerEmail;
    }
public void setBuyerOwnerId(final Long buyerOwnerId) {
        this.buyerOwnerId = buyerOwnerId;
    }
public void setBuyerOwnerName(final String buyerOwnerName) {
        this.buyerOwnerName = buyerOwnerName;
    }
public void setBuyerOwnerEmail(final String buyerOwnerEmail) {
        this.buyerOwnerEmail = buyerOwnerEmail;
    }
public void setSellerGymId(final Long sellerGymId) {
        this.sellerGymId = sellerGymId;
    }
public void setSellerGymName(final String sellerGymName) {
        this.sellerGymName = sellerGymName;
    }
public void setBuyerGymId(final Long buyerGymId) {
        this.buyerGymId = buyerGymId;
    }
public void setBuyerGymName(final String buyerGymName) {
        this.buyerGymName = buyerGymName;
    }
public void setEquipmentName(final String equipmentName) {
        this.equipmentName = equipmentName;
    }
public void setDetails(final String details) {
        this.details = details;
    }
public void setMonthlyRentPrice(final BigDecimal monthlyRentPrice) {
        this.monthlyRentPrice = monthlyRentPrice;
    }
public void setPurchasedAt(final LocalDateTime purchasedAt) {
        this.purchasedAt = purchasedAt;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EquipmentRentalTransactionResponse)) return false;
        final EquipmentRentalTransactionResponse other = (EquipmentRentalTransactionResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$sellerOwnerId = this.getSellerOwnerId();
        final java.lang.Object other$sellerOwnerId = other.getSellerOwnerId();
        if (this$sellerOwnerId == null ? other$sellerOwnerId != null : !this$sellerOwnerId.equals(other$sellerOwnerId)) return false;
        final java.lang.Object this$buyerOwnerId = this.getBuyerOwnerId();
        final java.lang.Object other$buyerOwnerId = other.getBuyerOwnerId();
        if (this$buyerOwnerId == null ? other$buyerOwnerId != null : !this$buyerOwnerId.equals(other$buyerOwnerId)) return false;
        final java.lang.Object this$sellerGymId = this.getSellerGymId();
        final java.lang.Object other$sellerGymId = other.getSellerGymId();
        if (this$sellerGymId == null ? other$sellerGymId != null : !this$sellerGymId.equals(other$sellerGymId)) return false;
        final java.lang.Object this$buyerGymId = this.getBuyerGymId();
        final java.lang.Object other$buyerGymId = other.getBuyerGymId();
        if (this$buyerGymId == null ? other$buyerGymId != null : !this$buyerGymId.equals(other$buyerGymId)) return false;
        final java.lang.Object this$sellerOwnerName = this.getSellerOwnerName();
        final java.lang.Object other$sellerOwnerName = other.getSellerOwnerName();
        if (this$sellerOwnerName == null ? other$sellerOwnerName != null : !this$sellerOwnerName.equals(other$sellerOwnerName)) return false;
        final java.lang.Object this$sellerOwnerEmail = this.getSellerOwnerEmail();
        final java.lang.Object other$sellerOwnerEmail = other.getSellerOwnerEmail();
        if (this$sellerOwnerEmail == null ? other$sellerOwnerEmail != null : !this$sellerOwnerEmail.equals(other$sellerOwnerEmail)) return false;
        final java.lang.Object this$buyerOwnerName = this.getBuyerOwnerName();
        final java.lang.Object other$buyerOwnerName = other.getBuyerOwnerName();
        if (this$buyerOwnerName == null ? other$buyerOwnerName != null : !this$buyerOwnerName.equals(other$buyerOwnerName)) return false;
        final java.lang.Object this$buyerOwnerEmail = this.getBuyerOwnerEmail();
        final java.lang.Object other$buyerOwnerEmail = other.getBuyerOwnerEmail();
        if (this$buyerOwnerEmail == null ? other$buyerOwnerEmail != null : !this$buyerOwnerEmail.equals(other$buyerOwnerEmail)) return false;
        final java.lang.Object this$sellerGymName = this.getSellerGymName();
        final java.lang.Object other$sellerGymName = other.getSellerGymName();
        if (this$sellerGymName == null ? other$sellerGymName != null : !this$sellerGymName.equals(other$sellerGymName)) return false;
        final java.lang.Object this$buyerGymName = this.getBuyerGymName();
        final java.lang.Object other$buyerGymName = other.getBuyerGymName();
        if (this$buyerGymName == null ? other$buyerGymName != null : !this$buyerGymName.equals(other$buyerGymName)) return false;
        final java.lang.Object this$equipmentName = this.getEquipmentName();
        final java.lang.Object other$equipmentName = other.getEquipmentName();
        if (this$equipmentName == null ? other$equipmentName != null : !this$equipmentName.equals(other$equipmentName)) return false;
        final java.lang.Object this$details = this.getDetails();
        final java.lang.Object other$details = other.getDetails();
        if (this$details == null ? other$details != null : !this$details.equals(other$details)) return false;
        final java.lang.Object this$monthlyRentPrice = this.getMonthlyRentPrice();
        final java.lang.Object other$monthlyRentPrice = other.getMonthlyRentPrice();
        if (this$monthlyRentPrice == null ? other$monthlyRentPrice != null : !this$monthlyRentPrice.equals(other$monthlyRentPrice)) return false;
        final java.lang.Object this$purchasedAt = this.getPurchasedAt();
        final java.lang.Object other$purchasedAt = other.getPurchasedAt();
        if (this$purchasedAt == null ? other$purchasedAt != null : !this$purchasedAt.equals(other$purchasedAt)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EquipmentRentalTransactionResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $sellerOwnerId = this.getSellerOwnerId();
        result = result * PRIME + ($sellerOwnerId == null ? 43 : $sellerOwnerId.hashCode());
        final java.lang.Object $buyerOwnerId = this.getBuyerOwnerId();
        result = result * PRIME + ($buyerOwnerId == null ? 43 : $buyerOwnerId.hashCode());
        final java.lang.Object $sellerGymId = this.getSellerGymId();
        result = result * PRIME + ($sellerGymId == null ? 43 : $sellerGymId.hashCode());
        final java.lang.Object $buyerGymId = this.getBuyerGymId();
        result = result * PRIME + ($buyerGymId == null ? 43 : $buyerGymId.hashCode());
        final java.lang.Object $sellerOwnerName = this.getSellerOwnerName();
        result = result * PRIME + ($sellerOwnerName == null ? 43 : $sellerOwnerName.hashCode());
        final java.lang.Object $sellerOwnerEmail = this.getSellerOwnerEmail();
        result = result * PRIME + ($sellerOwnerEmail == null ? 43 : $sellerOwnerEmail.hashCode());
        final java.lang.Object $buyerOwnerName = this.getBuyerOwnerName();
        result = result * PRIME + ($buyerOwnerName == null ? 43 : $buyerOwnerName.hashCode());
        final java.lang.Object $buyerOwnerEmail = this.getBuyerOwnerEmail();
        result = result * PRIME + ($buyerOwnerEmail == null ? 43 : $buyerOwnerEmail.hashCode());
        final java.lang.Object $sellerGymName = this.getSellerGymName();
        result = result * PRIME + ($sellerGymName == null ? 43 : $sellerGymName.hashCode());
        final java.lang.Object $buyerGymName = this.getBuyerGymName();
        result = result * PRIME + ($buyerGymName == null ? 43 : $buyerGymName.hashCode());
        final java.lang.Object $equipmentName = this.getEquipmentName();
        result = result * PRIME + ($equipmentName == null ? 43 : $equipmentName.hashCode());
        final java.lang.Object $details = this.getDetails();
        result = result * PRIME + ($details == null ? 43 : $details.hashCode());
        final java.lang.Object $monthlyRentPrice = this.getMonthlyRentPrice();
        result = result * PRIME + ($monthlyRentPrice == null ? 43 : $monthlyRentPrice.hashCode());
        final java.lang.Object $purchasedAt = this.getPurchasedAt();
        result = result * PRIME + ($purchasedAt == null ? 43 : $purchasedAt.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "EquipmentRentalTransactionResponse(id=" + this.getId() + ", sellerOwnerId=" + this.getSellerOwnerId() + ", sellerOwnerName=" + this.getSellerOwnerName() + ", sellerOwnerEmail=" + this.getSellerOwnerEmail() + ", buyerOwnerId=" + this.getBuyerOwnerId() + ", buyerOwnerName=" + this.getBuyerOwnerName() + ", buyerOwnerEmail=" + this.getBuyerOwnerEmail() + ", sellerGymId=" + this.getSellerGymId() + ", sellerGymName=" + this.getSellerGymName() + ", buyerGymId=" + this.getBuyerGymId() + ", buyerGymName=" + this.getBuyerGymName() + ", equipmentName=" + this.getEquipmentName() + ", details=" + this.getDetails() + ", monthlyRentPrice=" + this.getMonthlyRentPrice() + ", purchasedAt=" + this.getPurchasedAt() + ")";
    }
}
