// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import com.fitconnect.entity.enums.EquipmentCondition;

public class EquipmentResponse {
    private Long id;
    private Long gymId;
    private String equipmentName;
    private Integer quantity;
    private EquipmentCondition condition;
EquipmentResponse(final Long id, final Long gymId, final String equipmentName, final Integer quantity, final EquipmentCondition condition) {
        this.id = id;
        this.gymId = gymId;
        this.equipmentName = equipmentName;
        this.quantity = quantity;
        this.condition = condition;
    }
public static class EquipmentResponseBuilder {
private Long id;
private Long gymId;
private String equipmentName;
private Integer quantity;
private EquipmentCondition condition;
EquipmentResponseBuilder() {
        }
public EquipmentResponse.EquipmentResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public EquipmentResponse.EquipmentResponseBuilder gymId(final Long gymId) {
            this.gymId = gymId;
            return this;
        }
public EquipmentResponse.EquipmentResponseBuilder equipmentName(final String equipmentName) {
            this.equipmentName = equipmentName;
            return this;
        }
public EquipmentResponse.EquipmentResponseBuilder quantity(final Integer quantity) {
            this.quantity = quantity;
            return this;
        }
public EquipmentResponse.EquipmentResponseBuilder condition(final EquipmentCondition condition) {
            this.condition = condition;
            return this;
        }
public EquipmentResponse build() {
            return new EquipmentResponse(this.id, this.gymId, this.equipmentName, this.quantity, this.condition);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "EquipmentResponse.EquipmentResponseBuilder(id=" + this.id + ", gymId=" + this.gymId + ", equipmentName=" + this.equipmentName + ", quantity=" + this.quantity + ", condition=" + this.condition + ")";
        }
    }
public static EquipmentResponse.EquipmentResponseBuilder builder() {
        return new EquipmentResponse.EquipmentResponseBuilder();
    }
public Long getId() {
        return this.id;
    }
public Long getGymId() {
        return this.gymId;
    }
public String getEquipmentName() {
        return this.equipmentName;
    }
public Integer getQuantity() {
        return this.quantity;
    }
public EquipmentCondition getCondition() {
        return this.condition;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setGymId(final Long gymId) {
        this.gymId = gymId;
    }
public void setEquipmentName(final String equipmentName) {
        this.equipmentName = equipmentName;
    }
public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }
public void setCondition(final EquipmentCondition condition) {
        this.condition = condition;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EquipmentResponse)) return false;
        final EquipmentResponse other = (EquipmentResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$gymId = this.getGymId();
        final java.lang.Object other$gymId = other.getGymId();
        if (this$gymId == null ? other$gymId != null : !this$gymId.equals(other$gymId)) return false;
        final java.lang.Object this$quantity = this.getQuantity();
        final java.lang.Object other$quantity = other.getQuantity();
        if (this$quantity == null ? other$quantity != null : !this$quantity.equals(other$quantity)) return false;
        final java.lang.Object this$equipmentName = this.getEquipmentName();
        final java.lang.Object other$equipmentName = other.getEquipmentName();
        if (this$equipmentName == null ? other$equipmentName != null : !this$equipmentName.equals(other$equipmentName)) return false;
        final java.lang.Object this$condition = this.getCondition();
        final java.lang.Object other$condition = other.getCondition();
        if (this$condition == null ? other$condition != null : !this$condition.equals(other$condition)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EquipmentResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $gymId = this.getGymId();
        result = result * PRIME + ($gymId == null ? 43 : $gymId.hashCode());
        final java.lang.Object $quantity = this.getQuantity();
        result = result * PRIME + ($quantity == null ? 43 : $quantity.hashCode());
        final java.lang.Object $equipmentName = this.getEquipmentName();
        result = result * PRIME + ($equipmentName == null ? 43 : $equipmentName.hashCode());
        final java.lang.Object $condition = this.getCondition();
        result = result * PRIME + ($condition == null ? 43 : $condition.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "EquipmentResponse(id=" + this.getId() + ", gymId=" + this.getGymId() + ", equipmentName=" + this.getEquipmentName() + ", quantity=" + this.getQuantity() + ", condition=" + this.getCondition() + ")";
    }
}
