// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import java.util.List;

public class GymDetailsResponse {
    private Long id;
    private String name;
    private String location;
    private Double monthlyFee;
    private Double rating;
    private Integer reviewCount;
    private List<EquipmentResponse> equipment;
    private List<GymReviewResponse> reviews;
GymDetailsResponse(final Long id, final String name, final String location, final Double monthlyFee, final Double rating, final Integer reviewCount, final List<EquipmentResponse> equipment, final List<GymReviewResponse> reviews) {
        this.id = id;
        this.name = name;
        this.location = location;
        this.monthlyFee = monthlyFee;
        this.rating = rating;
        this.reviewCount = reviewCount;
        this.equipment = equipment;
        this.reviews = reviews;
    }
public static class GymDetailsResponseBuilder {
private Long id;
private String name;
private String location;
private Double monthlyFee;
private Double rating;
private Integer reviewCount;
private List<EquipmentResponse> equipment;
private List<GymReviewResponse> reviews;
GymDetailsResponseBuilder() {
        }
public GymDetailsResponse.GymDetailsResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public GymDetailsResponse.GymDetailsResponseBuilder name(final String name) {
            this.name = name;
            return this;
        }
public GymDetailsResponse.GymDetailsResponseBuilder location(final String location) {
            this.location = location;
            return this;
        }
public GymDetailsResponse.GymDetailsResponseBuilder monthlyFee(final Double monthlyFee) {
            this.monthlyFee = monthlyFee;
            return this;
        }
public GymDetailsResponse.GymDetailsResponseBuilder rating(final Double rating) {
            this.rating = rating;
            return this;
        }
public GymDetailsResponse.GymDetailsResponseBuilder reviewCount(final Integer reviewCount) {
            this.reviewCount = reviewCount;
            return this;
        }
public GymDetailsResponse.GymDetailsResponseBuilder equipment(final List<EquipmentResponse> equipment) {
            this.equipment = equipment;
            return this;
        }
public GymDetailsResponse.GymDetailsResponseBuilder reviews(final List<GymReviewResponse> reviews) {
            this.reviews = reviews;
            return this;
        }
public GymDetailsResponse build() {
            return new GymDetailsResponse(this.id, this.name, this.location, this.monthlyFee, this.rating, this.reviewCount, this.equipment, this.reviews);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "GymDetailsResponse.GymDetailsResponseBuilder(id=" + this.id + ", name=" + this.name + ", location=" + this.location + ", monthlyFee=" + this.monthlyFee + ", rating=" + this.rating + ", reviewCount=" + this.reviewCount + ", equipment=" + this.equipment + ", reviews=" + this.reviews + ")";
        }
    }
public static GymDetailsResponse.GymDetailsResponseBuilder builder() {
        return new GymDetailsResponse.GymDetailsResponseBuilder();
    }
public Long getId() {
        return this.id;
    }
public String getName() {
        return this.name;
    }
public String getLocation() {
        return this.location;
    }
public Double getMonthlyFee() {
        return this.monthlyFee;
    }
public Double getRating() {
        return this.rating;
    }
public Integer getReviewCount() {
        return this.reviewCount;
    }
public List<EquipmentResponse> getEquipment() {
        return this.equipment;
    }
public List<GymReviewResponse> getReviews() {
        return this.reviews;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setName(final String name) {
        this.name = name;
    }
public void setLocation(final String location) {
        this.location = location;
    }
public void setMonthlyFee(final Double monthlyFee) {
        this.monthlyFee = monthlyFee;
    }
public void setRating(final Double rating) {
        this.rating = rating;
    }
public void setReviewCount(final Integer reviewCount) {
        this.reviewCount = reviewCount;
    }
public void setEquipment(final List<EquipmentResponse> equipment) {
        this.equipment = equipment;
    }
public void setReviews(final List<GymReviewResponse> reviews) {
        this.reviews = reviews;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof GymDetailsResponse)) return false;
        final GymDetailsResponse other = (GymDetailsResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$monthlyFee = this.getMonthlyFee();
        final java.lang.Object other$monthlyFee = other.getMonthlyFee();
        if (this$monthlyFee == null ? other$monthlyFee != null : !this$monthlyFee.equals(other$monthlyFee)) return false;
        final java.lang.Object this$rating = this.getRating();
        final java.lang.Object other$rating = other.getRating();
        if (this$rating == null ? other$rating != null : !this$rating.equals(other$rating)) return false;
        final java.lang.Object this$reviewCount = this.getReviewCount();
        final java.lang.Object other$reviewCount = other.getReviewCount();
        if (this$reviewCount == null ? other$reviewCount != null : !this$reviewCount.equals(other$reviewCount)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$location = this.getLocation();
        final java.lang.Object other$location = other.getLocation();
        if (this$location == null ? other$location != null : !this$location.equals(other$location)) return false;
        final java.lang.Object this$equipment = this.getEquipment();
        final java.lang.Object other$equipment = other.getEquipment();
        if (this$equipment == null ? other$equipment != null : !this$equipment.equals(other$equipment)) return false;
        final java.lang.Object this$reviews = this.getReviews();
        final java.lang.Object other$reviews = other.getReviews();
        if (this$reviews == null ? other$reviews != null : !this$reviews.equals(other$reviews)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof GymDetailsResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $monthlyFee = this.getMonthlyFee();
        result = result * PRIME + ($monthlyFee == null ? 43 : $monthlyFee.hashCode());
        final java.lang.Object $rating = this.getRating();
        result = result * PRIME + ($rating == null ? 43 : $rating.hashCode());
        final java.lang.Object $reviewCount = this.getReviewCount();
        result = result * PRIME + ($reviewCount == null ? 43 : $reviewCount.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $location = this.getLocation();
        result = result * PRIME + ($location == null ? 43 : $location.hashCode());
        final java.lang.Object $equipment = this.getEquipment();
        result = result * PRIME + ($equipment == null ? 43 : $equipment.hashCode());
        final java.lang.Object $reviews = this.getReviews();
        result = result * PRIME + ($reviews == null ? 43 : $reviews.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "GymDetailsResponse(id=" + this.getId() + ", name=" + this.getName() + ", location=" + this.getLocation() + ", monthlyFee=" + this.getMonthlyFee() + ", rating=" + this.getRating() + ", reviewCount=" + this.getReviewCount() + ", equipment=" + this.getEquipment() + ", reviews=" + this.getReviews() + ")";
    }
}
