// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import com.fitconnect.entity.enums.MembershipStatus;

public class GymMemberResponse {
    private Long userId;
    private String name;
    private String email;
    private String planName;
    private MembershipStatus status;
GymMemberResponse(final Long userId, final String name, final String email, final String planName, final MembershipStatus status) {
        this.userId = userId;
        this.name = name;
        this.email = email;
        this.planName = planName;
        this.status = status;
    }
public static class GymMemberResponseBuilder {
private Long userId;
private String name;
private String email;
private String planName;
private MembershipStatus status;
GymMemberResponseBuilder() {
        }
public GymMemberResponse.GymMemberResponseBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }
public GymMemberResponse.GymMemberResponseBuilder name(final String name) {
            this.name = name;
            return this;
        }
public GymMemberResponse.GymMemberResponseBuilder email(final String email) {
            this.email = email;
            return this;
        }
public GymMemberResponse.GymMemberResponseBuilder planName(final String planName) {
            this.planName = planName;
            return this;
        }
public GymMemberResponse.GymMemberResponseBuilder status(final MembershipStatus status) {
            this.status = status;
            return this;
        }
public GymMemberResponse build() {
            return new GymMemberResponse(this.userId, this.name, this.email, this.planName, this.status);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "GymMemberResponse.GymMemberResponseBuilder(userId=" + this.userId + ", name=" + this.name + ", email=" + this.email + ", planName=" + this.planName + ", status=" + this.status + ")";
        }
    }
public static GymMemberResponse.GymMemberResponseBuilder builder() {
        return new GymMemberResponse.GymMemberResponseBuilder();
    }
public Long getUserId() {
        return this.userId;
    }
public String getName() {
        return this.name;
    }
public String getEmail() {
        return this.email;
    }
public String getPlanName() {
        return this.planName;
    }
public MembershipStatus getStatus() {
        return this.status;
    }
public void setUserId(final Long userId) {
        this.userId = userId;
    }
public void setName(final String name) {
        this.name = name;
    }
public void setEmail(final String email) {
        this.email = email;
    }
public void setPlanName(final String planName) {
        this.planName = planName;
    }
public void setStatus(final MembershipStatus status) {
        this.status = status;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof GymMemberResponse)) return false;
        final GymMemberResponse other = (GymMemberResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$planName = this.getPlanName();
        final java.lang.Object other$planName = other.getPlanName();
        if (this$planName == null ? other$planName != null : !this$planName.equals(other$planName)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof GymMemberResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $planName = this.getPlanName();
        result = result * PRIME + ($planName == null ? 43 : $planName.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "GymMemberResponse(userId=" + this.getUserId() + ", name=" + this.getName() + ", email=" + this.getEmail() + ", planName=" + this.getPlanName() + ", status=" + this.getStatus() + ")";
    }
}
