// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import java.math.BigDecimal;

public class GymMarketplaceHistoryResponse {
    private Integer year;
    private Integer month;
    private String label;
    private Integer soldCount;
    private Integer rentedCount;
    private BigDecimal soldAmount;
    private BigDecimal rentedAmount;
GymMarketplaceHistoryResponse(final Integer year, final Integer month, final String label, final Integer soldCount, final Integer rentedCount, final BigDecimal soldAmount, final BigDecimal rentedAmount) {
        this.year = year;
        this.month = month;
        this.label = label;
        this.soldCount = soldCount;
        this.rentedCount = rentedCount;
        this.soldAmount = soldAmount;
        this.rentedAmount = rentedAmount;
    }
public static class GymMarketplaceHistoryResponseBuilder {
private Integer year;
private Integer month;
private String label;
private Integer soldCount;
private Integer rentedCount;
private BigDecimal soldAmount;
private BigDecimal rentedAmount;
GymMarketplaceHistoryResponseBuilder() {
        }
public GymMarketplaceHistoryResponse.GymMarketplaceHistoryResponseBuilder year(final Integer year) {
            this.year = year;
            return this;
        }
public GymMarketplaceHistoryResponse.GymMarketplaceHistoryResponseBuilder month(final Integer month) {
            this.month = month;
            return this;
        }
public GymMarketplaceHistoryResponse.GymMarketplaceHistoryResponseBuilder label(final String label) {
            this.label = label;
            return this;
        }
public GymMarketplaceHistoryResponse.GymMarketplaceHistoryResponseBuilder soldCount(final Integer soldCount) {
            this.soldCount = soldCount;
            return this;
        }
public GymMarketplaceHistoryResponse.GymMarketplaceHistoryResponseBuilder rentedCount(final Integer rentedCount) {
            this.rentedCount = rentedCount;
            return this;
        }
public GymMarketplaceHistoryResponse.GymMarketplaceHistoryResponseBuilder soldAmount(final BigDecimal soldAmount) {
            this.soldAmount = soldAmount;
            return this;
        }
public GymMarketplaceHistoryResponse.GymMarketplaceHistoryResponseBuilder rentedAmount(final BigDecimal rentedAmount) {
            this.rentedAmount = rentedAmount;
            return this;
        }
public GymMarketplaceHistoryResponse build() {
            return new GymMarketplaceHistoryResponse(this.year, this.month, this.label, this.soldCount, this.rentedCount, this.soldAmount, this.rentedAmount);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "GymMarketplaceHistoryResponse.GymMarketplaceHistoryResponseBuilder(year=" + this.year + ", month=" + this.month + ", label=" + this.label + ", soldCount=" + this.soldCount + ", rentedCount=" + this.rentedCount + ", soldAmount=" + this.soldAmount + ", rentedAmount=" + this.rentedAmount + ")";
        }
    }
public static GymMarketplaceHistoryResponse.GymMarketplaceHistoryResponseBuilder builder() {
        return new GymMarketplaceHistoryResponse.GymMarketplaceHistoryResponseBuilder();
    }
public Integer getYear() {
        return this.year;
    }
public Integer getMonth() {
        return this.month;
    }
public String getLabel() {
        return this.label;
    }
public Integer getSoldCount() {
        return this.soldCount;
    }
public Integer getRentedCount() {
        return this.rentedCount;
    }
public BigDecimal getSoldAmount() {
        return this.soldAmount;
    }
public BigDecimal getRentedAmount() {
        return this.rentedAmount;
    }
public void setYear(final Integer year) {
        this.year = year;
    }
public void setMonth(final Integer month) {
        this.month = month;
    }
public void setLabel(final String label) {
        this.label = label;
    }
public void setSoldCount(final Integer soldCount) {
        this.soldCount = soldCount;
    }
public void setRentedCount(final Integer rentedCount) {
        this.rentedCount = rentedCount;
    }
public void setSoldAmount(final BigDecimal soldAmount) {
        this.soldAmount = soldAmount;
    }
public void setRentedAmount(final BigDecimal rentedAmount) {
        this.rentedAmount = rentedAmount;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof GymMarketplaceHistoryResponse)) return false;
        final GymMarketplaceHistoryResponse other = (GymMarketplaceHistoryResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$year = this.getYear();
        final java.lang.Object other$year = other.getYear();
        if (this$year == null ? other$year != null : !this$year.equals(other$year)) return false;
        final java.lang.Object this$month = this.getMonth();
        final java.lang.Object other$month = other.getMonth();
        if (this$month == null ? other$month != null : !this$month.equals(other$month)) return false;
        final java.lang.Object this$soldCount = this.getSoldCount();
        final java.lang.Object other$soldCount = other.getSoldCount();
        if (this$soldCount == null ? other$soldCount != null : !this$soldCount.equals(other$soldCount)) return false;
        final java.lang.Object this$rentedCount = this.getRentedCount();
        final java.lang.Object other$rentedCount = other.getRentedCount();
        if (this$rentedCount == null ? other$rentedCount != null : !this$rentedCount.equals(other$rentedCount)) return false;
        final java.lang.Object this$label = this.getLabel();
        final java.lang.Object other$label = other.getLabel();
        if (this$label == null ? other$label != null : !this$label.equals(other$label)) return false;
        final java.lang.Object this$soldAmount = this.getSoldAmount();
        final java.lang.Object other$soldAmount = other.getSoldAmount();
        if (this$soldAmount == null ? other$soldAmount != null : !this$soldAmount.equals(other$soldAmount)) return false;
        final java.lang.Object this$rentedAmount = this.getRentedAmount();
        final java.lang.Object other$rentedAmount = other.getRentedAmount();
        if (this$rentedAmount == null ? other$rentedAmount != null : !this$rentedAmount.equals(other$rentedAmount)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof GymMarketplaceHistoryResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $year = this.getYear();
        result = result * PRIME + ($year == null ? 43 : $year.hashCode());
        final java.lang.Object $month = this.getMonth();
        result = result * PRIME + ($month == null ? 43 : $month.hashCode());
        final java.lang.Object $soldCount = this.getSoldCount();
        result = result * PRIME + ($soldCount == null ? 43 : $soldCount.hashCode());
        final java.lang.Object $rentedCount = this.getRentedCount();
        result = result * PRIME + ($rentedCount == null ? 43 : $rentedCount.hashCode());
        final java.lang.Object $label = this.getLabel();
        result = result * PRIME + ($label == null ? 43 : $label.hashCode());
        final java.lang.Object $soldAmount = this.getSoldAmount();
        result = result * PRIME + ($soldAmount == null ? 43 : $soldAmount.hashCode());
        final java.lang.Object $rentedAmount = this.getRentedAmount();
        result = result * PRIME + ($rentedAmount == null ? 43 : $rentedAmount.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "GymMarketplaceHistoryResponse(year=" + this.getYear() + ", month=" + this.getMonth() + ", label=" + this.getLabel() + ", soldCount=" + this.getSoldCount() + ", rentedCount=" + this.getRentedCount() + ", soldAmount=" + this.getSoldAmount() + ", rentedAmount=" + this.getRentedAmount() + ")";
    }
}
