// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;

public class GymReviewRequest {
    @Min(1)
    @Max(5)
    private Integer rating;
    @NotBlank
    private String comment;
public GymReviewRequest() {
    }
public Integer getRating() {
        return this.rating;
    }
public String getComment() {
        return this.comment;
    }
public void setRating(final Integer rating) {
        this.rating = rating;
    }
public void setComment(final String comment) {
        this.comment = comment;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof GymReviewRequest)) return false;
        final GymReviewRequest other = (GymReviewRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$rating = this.getRating();
        final java.lang.Object other$rating = other.getRating();
        if (this$rating == null ? other$rating != null : !this$rating.equals(other$rating)) return false;
        final java.lang.Object this$comment = this.getComment();
        final java.lang.Object other$comment = other.getComment();
        if (this$comment == null ? other$comment != null : !this$comment.equals(other$comment)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof GymReviewRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $rating = this.getRating();
        result = result * PRIME + ($rating == null ? 43 : $rating.hashCode());
        final java.lang.Object $comment = this.getComment();
        result = result * PRIME + ($comment == null ? 43 : $comment.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "GymReviewRequest(rating=" + this.getRating() + ", comment=" + this.getComment() + ")";
    }
}
