// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import java.time.LocalDateTime;

public class GymReviewResponse {
    private Long id;
    private Long gymId;
    private Long userId;
    private String userName;
    private Integer rating;
    private String comment;
    private LocalDateTime createdAt;
GymReviewResponse(final Long id, final Long gymId, final Long userId, final String userName, final Integer rating, final String comment, final LocalDateTime createdAt) {
        this.id = id;
        this.gymId = gymId;
        this.userId = userId;
        this.userName = userName;
        this.rating = rating;
        this.comment = comment;
        this.createdAt = createdAt;
    }
public static class GymReviewResponseBuilder {
private Long id;
private Long gymId;
private Long userId;
private String userName;
private Integer rating;
private String comment;
private LocalDateTime createdAt;
GymReviewResponseBuilder() {
        }
public GymReviewResponse.GymReviewResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public GymReviewResponse.GymReviewResponseBuilder gymId(final Long gymId) {
            this.gymId = gymId;
            return this;
        }
public GymReviewResponse.GymReviewResponseBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }
public GymReviewResponse.GymReviewResponseBuilder userName(final String userName) {
            this.userName = userName;
            return this;
        }
public GymReviewResponse.GymReviewResponseBuilder rating(final Integer rating) {
            this.rating = rating;
            return this;
        }
public GymReviewResponse.GymReviewResponseBuilder comment(final String comment) {
            this.comment = comment;
            return this;
        }
public GymReviewResponse.GymReviewResponseBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }
public GymReviewResponse build() {
            return new GymReviewResponse(this.id, this.gymId, this.userId, this.userName, this.rating, this.comment, this.createdAt);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "GymReviewResponse.GymReviewResponseBuilder(id=" + this.id + ", gymId=" + this.gymId + ", userId=" + this.userId + ", userName=" + this.userName + ", rating=" + this.rating + ", comment=" + this.comment + ", createdAt=" + this.createdAt + ")";
        }
    }
public static GymReviewResponse.GymReviewResponseBuilder builder() {
        return new GymReviewResponse.GymReviewResponseBuilder();
    }
public Long getId() {
        return this.id;
    }
public Long getGymId() {
        return this.gymId;
    }
public Long getUserId() {
        return this.userId;
    }
public String getUserName() {
        return this.userName;
    }
public Integer getRating() {
        return this.rating;
    }
public String getComment() {
        return this.comment;
    }
public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setGymId(final Long gymId) {
        this.gymId = gymId;
    }
public void setUserId(final Long userId) {
        this.userId = userId;
    }
public void setUserName(final String userName) {
        this.userName = userName;
    }
public void setRating(final Integer rating) {
        this.rating = rating;
    }
public void setComment(final String comment) {
        this.comment = comment;
    }
public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof GymReviewResponse)) return false;
        final GymReviewResponse other = (GymReviewResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$gymId = this.getGymId();
        final java.lang.Object other$gymId = other.getGymId();
        if (this$gymId == null ? other$gymId != null : !this$gymId.equals(other$gymId)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$rating = this.getRating();
        final java.lang.Object other$rating = other.getRating();
        if (this$rating == null ? other$rating != null : !this$rating.equals(other$rating)) return false;
        final java.lang.Object this$userName = this.getUserName();
        final java.lang.Object other$userName = other.getUserName();
        if (this$userName == null ? other$userName != null : !this$userName.equals(other$userName)) return false;
        final java.lang.Object this$comment = this.getComment();
        final java.lang.Object other$comment = other.getComment();
        if (this$comment == null ? other$comment != null : !this$comment.equals(other$comment)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof GymReviewResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $gymId = this.getGymId();
        result = result * PRIME + ($gymId == null ? 43 : $gymId.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $rating = this.getRating();
        result = result * PRIME + ($rating == null ? 43 : $rating.hashCode());
        final java.lang.Object $userName = this.getUserName();
        result = result * PRIME + ($userName == null ? 43 : $userName.hashCode());
        final java.lang.Object $comment = this.getComment();
        result = result * PRIME + ($comment == null ? 43 : $comment.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "GymReviewResponse(id=" + this.getId() + ", gymId=" + this.getGymId() + ", userId=" + this.getUserId() + ", userName=" + this.getUserName() + ", rating=" + this.getRating() + ", comment=" + this.getComment() + ", createdAt=" + this.getCreatedAt() + ")";
    }
}
