// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

public class GymRequest {
    @NotBlank
    private String name;
    @NotBlank
    private String location;
    @NotNull
    @Positive
    private Double monthlyFee;
public GymRequest() {
    }
public String getName() {
        return this.name;
    }
public String getLocation() {
        return this.location;
    }
public Double getMonthlyFee() {
        return this.monthlyFee;
    }
public void setName(final String name) {
        this.name = name;
    }
public void setLocation(final String location) {
        this.location = location;
    }
public void setMonthlyFee(final Double monthlyFee) {
        this.monthlyFee = monthlyFee;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof GymRequest)) return false;
        final GymRequest other = (GymRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$monthlyFee = this.getMonthlyFee();
        final java.lang.Object other$monthlyFee = other.getMonthlyFee();
        if (this$monthlyFee == null ? other$monthlyFee != null : !this$monthlyFee.equals(other$monthlyFee)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$location = this.getLocation();
        final java.lang.Object other$location = other.getLocation();
        if (this$location == null ? other$location != null : !this$location.equals(other$location)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof GymRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $monthlyFee = this.getMonthlyFee();
        result = result * PRIME + ($monthlyFee == null ? 43 : $monthlyFee.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $location = this.getLocation();
        result = result * PRIME + ($location == null ? 43 : $location.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "GymRequest(name=" + this.getName() + ", location=" + this.getLocation() + ", monthlyFee=" + this.getMonthlyFee() + ")";
    }
}
