// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import com.fitconnect.entity.enums.MembershipStatus;
import java.math.BigDecimal;
import java.time.LocalDate;

public class MembershipResponse {
    private Long id;
    private Long userId;
    private String userName;
    private Long gymId;
    private String gymName;
    private String planName;
    private Integer durationMonths;
    private BigDecimal amount;
    private LocalDate startDate;
    private LocalDate endDate;
    private MembershipStatus status;
MembershipResponse(final Long id, final Long userId, final String userName, final Long gymId, final String gymName, final String planName, final Integer durationMonths, final BigDecimal amount, final LocalDate startDate, final LocalDate endDate, final MembershipStatus status) {
        this.id = id;
        this.userId = userId;
        this.userName = userName;
        this.gymId = gymId;
        this.gymName = gymName;
        this.planName = planName;
        this.durationMonths = durationMonths;
        this.amount = amount;
        this.startDate = startDate;
        this.endDate = endDate;
        this.status = status;
    }
public static class MembershipResponseBuilder {
private Long id;
private Long userId;
private String userName;
private Long gymId;
private String gymName;
private String planName;
private Integer durationMonths;
private BigDecimal amount;
private LocalDate startDate;
private LocalDate endDate;
private MembershipStatus status;
MembershipResponseBuilder() {
        }
public MembershipResponse.MembershipResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public MembershipResponse.MembershipResponseBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }
public MembershipResponse.MembershipResponseBuilder userName(final String userName) {
            this.userName = userName;
            return this;
        }
public MembershipResponse.MembershipResponseBuilder gymId(final Long gymId) {
            this.gymId = gymId;
            return this;
        }
public MembershipResponse.MembershipResponseBuilder gymName(final String gymName) {
            this.gymName = gymName;
            return this;
        }
public MembershipResponse.MembershipResponseBuilder planName(final String planName) {
            this.planName = planName;
            return this;
        }
public MembershipResponse.MembershipResponseBuilder durationMonths(final Integer durationMonths) {
            this.durationMonths = durationMonths;
            return this;
        }
public MembershipResponse.MembershipResponseBuilder amount(final BigDecimal amount) {
            this.amount = amount;
            return this;
        }
public MembershipResponse.MembershipResponseBuilder startDate(final LocalDate startDate) {
            this.startDate = startDate;
            return this;
        }
public MembershipResponse.MembershipResponseBuilder endDate(final LocalDate endDate) {
            this.endDate = endDate;
            return this;
        }
public MembershipResponse.MembershipResponseBuilder status(final MembershipStatus status) {
            this.status = status;
            return this;
        }
public MembershipResponse build() {
            return new MembershipResponse(this.id, this.userId, this.userName, this.gymId, this.gymName, this.planName, this.durationMonths, this.amount, this.startDate, this.endDate, this.status);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "MembershipResponse.MembershipResponseBuilder(id=" + this.id + ", userId=" + this.userId + ", userName=" + this.userName + ", gymId=" + this.gymId + ", gymName=" + this.gymName + ", planName=" + this.planName + ", durationMonths=" + this.durationMonths + ", amount=" + this.amount + ", startDate=" + this.startDate + ", endDate=" + this.endDate + ", status=" + this.status + ")";
        }
    }
public static MembershipResponse.MembershipResponseBuilder builder() {
        return new MembershipResponse.MembershipResponseBuilder();
    }
public Long getId() {
        return this.id;
    }
public Long getUserId() {
        return this.userId;
    }
public String getUserName() {
        return this.userName;
    }
public Long getGymId() {
        return this.gymId;
    }
public String getGymName() {
        return this.gymName;
    }
public String getPlanName() {
        return this.planName;
    }
public Integer getDurationMonths() {
        return this.durationMonths;
    }
public BigDecimal getAmount() {
        return this.amount;
    }
public LocalDate getStartDate() {
        return this.startDate;
    }
public LocalDate getEndDate() {
        return this.endDate;
    }
public MembershipStatus getStatus() {
        return this.status;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setUserId(final Long userId) {
        this.userId = userId;
    }
public void setUserName(final String userName) {
        this.userName = userName;
    }
public void setGymId(final Long gymId) {
        this.gymId = gymId;
    }
public void setGymName(final String gymName) {
        this.gymName = gymName;
    }
public void setPlanName(final String planName) {
        this.planName = planName;
    }
public void setDurationMonths(final Integer durationMonths) {
        this.durationMonths = durationMonths;
    }
public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }
public void setStartDate(final LocalDate startDate) {
        this.startDate = startDate;
    }
public void setEndDate(final LocalDate endDate) {
        this.endDate = endDate;
    }
public void setStatus(final MembershipStatus status) {
        this.status = status;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MembershipResponse)) return false;
        final MembershipResponse other = (MembershipResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$gymId = this.getGymId();
        final java.lang.Object other$gymId = other.getGymId();
        if (this$gymId == null ? other$gymId != null : !this$gymId.equals(other$gymId)) return false;
        final java.lang.Object this$durationMonths = this.getDurationMonths();
        final java.lang.Object other$durationMonths = other.getDurationMonths();
        if (this$durationMonths == null ? other$durationMonths != null : !this$durationMonths.equals(other$durationMonths)) return false;
        final java.lang.Object this$userName = this.getUserName();
        final java.lang.Object other$userName = other.getUserName();
        if (this$userName == null ? other$userName != null : !this$userName.equals(other$userName)) return false;
        final java.lang.Object this$gymName = this.getGymName();
        final java.lang.Object other$gymName = other.getGymName();
        if (this$gymName == null ? other$gymName != null : !this$gymName.equals(other$gymName)) return false;
        final java.lang.Object this$planName = this.getPlanName();
        final java.lang.Object other$planName = other.getPlanName();
        if (this$planName == null ? other$planName != null : !this$planName.equals(other$planName)) return false;
        final java.lang.Object this$amount = this.getAmount();
        final java.lang.Object other$amount = other.getAmount();
        if (this$amount == null ? other$amount != null : !this$amount.equals(other$amount)) return false;
        final java.lang.Object this$startDate = this.getStartDate();
        final java.lang.Object other$startDate = other.getStartDate();
        if (this$startDate == null ? other$startDate != null : !this$startDate.equals(other$startDate)) return false;
        final java.lang.Object this$endDate = this.getEndDate();
        final java.lang.Object other$endDate = other.getEndDate();
        if (this$endDate == null ? other$endDate != null : !this$endDate.equals(other$endDate)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MembershipResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $gymId = this.getGymId();
        result = result * PRIME + ($gymId == null ? 43 : $gymId.hashCode());
        final java.lang.Object $durationMonths = this.getDurationMonths();
        result = result * PRIME + ($durationMonths == null ? 43 : $durationMonths.hashCode());
        final java.lang.Object $userName = this.getUserName();
        result = result * PRIME + ($userName == null ? 43 : $userName.hashCode());
        final java.lang.Object $gymName = this.getGymName();
        result = result * PRIME + ($gymName == null ? 43 : $gymName.hashCode());
        final java.lang.Object $planName = this.getPlanName();
        result = result * PRIME + ($planName == null ? 43 : $planName.hashCode());
        final java.lang.Object $amount = this.getAmount();
        result = result * PRIME + ($amount == null ? 43 : $amount.hashCode());
        final java.lang.Object $startDate = this.getStartDate();
        result = result * PRIME + ($startDate == null ? 43 : $startDate.hashCode());
        final java.lang.Object $endDate = this.getEndDate();
        result = result * PRIME + ($endDate == null ? 43 : $endDate.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "MembershipResponse(id=" + this.getId() + ", userId=" + this.getUserId() + ", userName=" + this.getUserName() + ", gymId=" + this.getGymId() + ", gymName=" + this.getGymName() + ", planName=" + this.getPlanName() + ", durationMonths=" + this.getDurationMonths() + ", amount=" + this.getAmount() + ", startDate=" + this.getStartDate() + ", endDate=" + this.getEndDate() + ", status=" + this.getStatus() + ")";
    }
}
