// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import com.fitconnect.entity.enums.MembershipStatus;
import jakarta.validation.constraints.NotNull;

public class MembershipStatusUpdateRequest {
    @NotNull
    private MembershipStatus status;
public MembershipStatusUpdateRequest() {
    }
public MembershipStatus getStatus() {
        return this.status;
    }
public void setStatus(final MembershipStatus status) {
        this.status = status;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MembershipStatusUpdateRequest)) return false;
        final MembershipStatusUpdateRequest other = (MembershipStatusUpdateRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MembershipStatusUpdateRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "MembershipStatusUpdateRequest(status=" + this.getStatus() + ")";
    }
}
