// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

public class MembershipPlanOptionResponse {
    private String planName;
    private String description;
    private Double multiplier;
    private Integer minimumMonths;
MembershipPlanOptionResponse(final String planName, final String description, final Double multiplier, final Integer minimumMonths) {
        this.planName = planName;
        this.description = description;
        this.multiplier = multiplier;
        this.minimumMonths = minimumMonths;
    }
public static class MembershipPlanOptionResponseBuilder {
private String planName;
private String description;
private Double multiplier;
private Integer minimumMonths;
MembershipPlanOptionResponseBuilder() {
        }
public MembershipPlanOptionResponse.MembershipPlanOptionResponseBuilder planName(final String planName) {
            this.planName = planName;
            return this;
        }
public MembershipPlanOptionResponse.MembershipPlanOptionResponseBuilder description(final String description) {
            this.description = description;
            return this;
        }
public MembershipPlanOptionResponse.MembershipPlanOptionResponseBuilder multiplier(final Double multiplier) {
            this.multiplier = multiplier;
            return this;
        }
public MembershipPlanOptionResponse.MembershipPlanOptionResponseBuilder minimumMonths(final Integer minimumMonths) {
            this.minimumMonths = minimumMonths;
            return this;
        }
public MembershipPlanOptionResponse build() {
            return new MembershipPlanOptionResponse(this.planName, this.description, this.multiplier, this.minimumMonths);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "MembershipPlanOptionResponse.MembershipPlanOptionResponseBuilder(planName=" + this.planName + ", description=" + this.description + ", multiplier=" + this.multiplier + ", minimumMonths=" + this.minimumMonths + ")";
        }
    }
public static MembershipPlanOptionResponse.MembershipPlanOptionResponseBuilder builder() {
        return new MembershipPlanOptionResponse.MembershipPlanOptionResponseBuilder();
    }
public String getPlanName() {
        return this.planName;
    }
public String getDescription() {
        return this.description;
    }
public Double getMultiplier() {
        return this.multiplier;
    }
public Integer getMinimumMonths() {
        return this.minimumMonths;
    }
public void setPlanName(final String planName) {
        this.planName = planName;
    }
public void setDescription(final String description) {
        this.description = description;
    }
public void setMultiplier(final Double multiplier) {
        this.multiplier = multiplier;
    }
public void setMinimumMonths(final Integer minimumMonths) {
        this.minimumMonths = minimumMonths;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MembershipPlanOptionResponse)) return false;
        final MembershipPlanOptionResponse other = (MembershipPlanOptionResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$multiplier = this.getMultiplier();
        final java.lang.Object other$multiplier = other.getMultiplier();
        if (this$multiplier == null ? other$multiplier != null : !this$multiplier.equals(other$multiplier)) return false;
        final java.lang.Object this$minimumMonths = this.getMinimumMonths();
        final java.lang.Object other$minimumMonths = other.getMinimumMonths();
        if (this$minimumMonths == null ? other$minimumMonths != null : !this$minimumMonths.equals(other$minimumMonths)) return false;
        final java.lang.Object this$planName = this.getPlanName();
        final java.lang.Object other$planName = other.getPlanName();
        if (this$planName == null ? other$planName != null : !this$planName.equals(other$planName)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MembershipPlanOptionResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $multiplier = this.getMultiplier();
        result = result * PRIME + ($multiplier == null ? 43 : $multiplier.hashCode());
        final java.lang.Object $minimumMonths = this.getMinimumMonths();
        result = result * PRIME + ($minimumMonths == null ? 43 : $minimumMonths.hashCode());
        final java.lang.Object $planName = this.getPlanName();
        result = result * PRIME + ($planName == null ? 43 : $planName.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "MembershipPlanOptionResponse(planName=" + this.getPlanName() + ", description=" + this.getDescription() + ", multiplier=" + this.getMultiplier() + ", minimumMonths=" + this.getMinimumMonths() + ")";
    }
}
