// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;

public class MembershipRequest {
    @NotNull
    private Long gymId;
    @NotNull
    private String planName;
    @NotNull
    @Min(1)
    private Integer durationMonths;
public MembershipRequest() {
    }
public Long getGymId() {
        return this.gymId;
    }
public String getPlanName() {
        return this.planName;
    }
public Integer getDurationMonths() {
        return this.durationMonths;
    }
public void setGymId(final Long gymId) {
        this.gymId = gymId;
    }
public void setPlanName(final String planName) {
        this.planName = planName;
    }
public void setDurationMonths(final Integer durationMonths) {
        this.durationMonths = durationMonths;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MembershipRequest)) return false;
        final MembershipRequest other = (MembershipRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$gymId = this.getGymId();
        final java.lang.Object other$gymId = other.getGymId();
        if (this$gymId == null ? other$gymId != null : !this$gymId.equals(other$gymId)) return false;
        final java.lang.Object this$durationMonths = this.getDurationMonths();
        final java.lang.Object other$durationMonths = other.getDurationMonths();
        if (this$durationMonths == null ? other$durationMonths != null : !this$durationMonths.equals(other$durationMonths)) return false;
        final java.lang.Object this$planName = this.getPlanName();
        final java.lang.Object other$planName = other.getPlanName();
        if (this$planName == null ? other$planName != null : !this$planName.equals(other$planName)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MembershipRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $gymId = this.getGymId();
        result = result * PRIME + ($gymId == null ? 43 : $gymId.hashCode());
        final java.lang.Object $durationMonths = this.getDurationMonths();
        result = result * PRIME + ($durationMonths == null ? 43 : $durationMonths.hashCode());
        final java.lang.Object $planName = this.getPlanName();
        result = result * PRIME + ($planName == null ? 43 : $planName.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "MembershipRequest(gymId=" + this.getGymId() + ", planName=" + this.getPlanName() + ", durationMonths=" + this.getDurationMonths() + ")";
    }
}
