// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

public class MessageResponse {
    private String message;
public String getMessage() {
        return this.message;
    }
public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MessageResponse)) return false;
        final MessageResponse other = (MessageResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MessageResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "MessageResponse(message=" + this.getMessage() + ")";
    }
public MessageResponse(final String message) {
        this.message = message;
    }
}
