// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import java.math.BigDecimal;

public class MonthlyRevenueResponse {
    private Integer year;
    private Integer month;
    private String label;
    private BigDecimal membershipRevenue;
    private BigDecimal marketplaceRevenue;
    private BigDecimal totalRevenue;
MonthlyRevenueResponse(final Integer year, final Integer month, final String label, final BigDecimal membershipRevenue, final BigDecimal marketplaceRevenue, final BigDecimal totalRevenue) {
        this.year = year;
        this.month = month;
        this.label = label;
        this.membershipRevenue = membershipRevenue;
        this.marketplaceRevenue = marketplaceRevenue;
        this.totalRevenue = totalRevenue;
    }
public static class MonthlyRevenueResponseBuilder {
private Integer year;
private Integer month;
private String label;
private BigDecimal membershipRevenue;
private BigDecimal marketplaceRevenue;
private BigDecimal totalRevenue;
MonthlyRevenueResponseBuilder() {
        }
public MonthlyRevenueResponse.MonthlyRevenueResponseBuilder year(final Integer year) {
            this.year = year;
            return this;
        }
public MonthlyRevenueResponse.MonthlyRevenueResponseBuilder month(final Integer month) {
            this.month = month;
            return this;
        }
public MonthlyRevenueResponse.MonthlyRevenueResponseBuilder label(final String label) {
            this.label = label;
            return this;
        }
public MonthlyRevenueResponse.MonthlyRevenueResponseBuilder membershipRevenue(final BigDecimal membershipRevenue) {
            this.membershipRevenue = membershipRevenue;
            return this;
        }
public MonthlyRevenueResponse.MonthlyRevenueResponseBuilder marketplaceRevenue(final BigDecimal marketplaceRevenue) {
            this.marketplaceRevenue = marketplaceRevenue;
            return this;
        }
public MonthlyRevenueResponse.MonthlyRevenueResponseBuilder totalRevenue(final BigDecimal totalRevenue) {
            this.totalRevenue = totalRevenue;
            return this;
        }
public MonthlyRevenueResponse build() {
            return new MonthlyRevenueResponse(this.year, this.month, this.label, this.membershipRevenue, this.marketplaceRevenue, this.totalRevenue);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "MonthlyRevenueResponse.MonthlyRevenueResponseBuilder(year=" + this.year + ", month=" + this.month + ", label=" + this.label + ", membershipRevenue=" + this.membershipRevenue + ", marketplaceRevenue=" + this.marketplaceRevenue + ", totalRevenue=" + this.totalRevenue + ")";
        }
    }
public static MonthlyRevenueResponse.MonthlyRevenueResponseBuilder builder() {
        return new MonthlyRevenueResponse.MonthlyRevenueResponseBuilder();
    }
public Integer getYear() {
        return this.year;
    }
public Integer getMonth() {
        return this.month;
    }
public String getLabel() {
        return this.label;
    }
public BigDecimal getMembershipRevenue() {
        return this.membershipRevenue;
    }
public BigDecimal getMarketplaceRevenue() {
        return this.marketplaceRevenue;
    }
public BigDecimal getTotalRevenue() {
        return this.totalRevenue;
    }
public void setYear(final Integer year) {
        this.year = year;
    }
public void setMonth(final Integer month) {
        this.month = month;
    }
public void setLabel(final String label) {
        this.label = label;
    }
public void setMembershipRevenue(final BigDecimal membershipRevenue) {
        this.membershipRevenue = membershipRevenue;
    }
public void setMarketplaceRevenue(final BigDecimal marketplaceRevenue) {
        this.marketplaceRevenue = marketplaceRevenue;
    }
public void setTotalRevenue(final BigDecimal totalRevenue) {
        this.totalRevenue = totalRevenue;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MonthlyRevenueResponse)) return false;
        final MonthlyRevenueResponse other = (MonthlyRevenueResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$year = this.getYear();
        final java.lang.Object other$year = other.getYear();
        if (this$year == null ? other$year != null : !this$year.equals(other$year)) return false;
        final java.lang.Object this$month = this.getMonth();
        final java.lang.Object other$month = other.getMonth();
        if (this$month == null ? other$month != null : !this$month.equals(other$month)) return false;
        final java.lang.Object this$label = this.getLabel();
        final java.lang.Object other$label = other.getLabel();
        if (this$label == null ? other$label != null : !this$label.equals(other$label)) return false;
        final java.lang.Object this$membershipRevenue = this.getMembershipRevenue();
        final java.lang.Object other$membershipRevenue = other.getMembershipRevenue();
        if (this$membershipRevenue == null ? other$membershipRevenue != null : !this$membershipRevenue.equals(other$membershipRevenue)) return false;
        final java.lang.Object this$marketplaceRevenue = this.getMarketplaceRevenue();
        final java.lang.Object other$marketplaceRevenue = other.getMarketplaceRevenue();
        if (this$marketplaceRevenue == null ? other$marketplaceRevenue != null : !this$marketplaceRevenue.equals(other$marketplaceRevenue)) return false;
        final java.lang.Object this$totalRevenue = this.getTotalRevenue();
        final java.lang.Object other$totalRevenue = other.getTotalRevenue();
        if (this$totalRevenue == null ? other$totalRevenue != null : !this$totalRevenue.equals(other$totalRevenue)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MonthlyRevenueResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $year = this.getYear();
        result = result * PRIME + ($year == null ? 43 : $year.hashCode());
        final java.lang.Object $month = this.getMonth();
        result = result * PRIME + ($month == null ? 43 : $month.hashCode());
        final java.lang.Object $label = this.getLabel();
        result = result * PRIME + ($label == null ? 43 : $label.hashCode());
        final java.lang.Object $membershipRevenue = this.getMembershipRevenue();
        result = result * PRIME + ($membershipRevenue == null ? 43 : $membershipRevenue.hashCode());
        final java.lang.Object $marketplaceRevenue = this.getMarketplaceRevenue();
        result = result * PRIME + ($marketplaceRevenue == null ? 43 : $marketplaceRevenue.hashCode());
        final java.lang.Object $totalRevenue = this.getTotalRevenue();
        result = result * PRIME + ($totalRevenue == null ? 43 : $totalRevenue.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "MonthlyRevenueResponse(year=" + this.getYear() + ", month=" + this.getMonth() + ", label=" + this.getLabel() + ", membershipRevenue=" + this.getMembershipRevenue() + ", marketplaceRevenue=" + this.getMarketplaceRevenue() + ", totalRevenue=" + this.getTotalRevenue() + ")";
    }
}
