// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import com.fitconnect.entity.enums.PaymentStatus;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public class PaymentResponse {
    private Long id;
    private Long userId;
    private String userName;
    private Long gymId;
    private String gymName;
    private BigDecimal amount;
    private PaymentStatus status;
    private LocalDateTime paidAt;
PaymentResponse(final Long id, final Long userId, final String userName, final Long gymId, final String gymName, final BigDecimal amount, final PaymentStatus status, final LocalDateTime paidAt) {
        this.id = id;
        this.userId = userId;
        this.userName = userName;
        this.gymId = gymId;
        this.gymName = gymName;
        this.amount = amount;
        this.status = status;
        this.paidAt = paidAt;
    }
public static class PaymentResponseBuilder {
private Long id;
private Long userId;
private String userName;
private Long gymId;
private String gymName;
private BigDecimal amount;
private PaymentStatus status;
private LocalDateTime paidAt;
PaymentResponseBuilder() {
        }
public PaymentResponse.PaymentResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public PaymentResponse.PaymentResponseBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }
public PaymentResponse.PaymentResponseBuilder userName(final String userName) {
            this.userName = userName;
            return this;
        }
public PaymentResponse.PaymentResponseBuilder gymId(final Long gymId) {
            this.gymId = gymId;
            return this;
        }
public PaymentResponse.PaymentResponseBuilder gymName(final String gymName) {
            this.gymName = gymName;
            return this;
        }
public PaymentResponse.PaymentResponseBuilder amount(final BigDecimal amount) {
            this.amount = amount;
            return this;
        }
public PaymentResponse.PaymentResponseBuilder status(final PaymentStatus status) {
            this.status = status;
            return this;
        }
public PaymentResponse.PaymentResponseBuilder paidAt(final LocalDateTime paidAt) {
            this.paidAt = paidAt;
            return this;
        }
public PaymentResponse build() {
            return new PaymentResponse(this.id, this.userId, this.userName, this.gymId, this.gymName, this.amount, this.status, this.paidAt);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "PaymentResponse.PaymentResponseBuilder(id=" + this.id + ", userId=" + this.userId + ", userName=" + this.userName + ", gymId=" + this.gymId + ", gymName=" + this.gymName + ", amount=" + this.amount + ", status=" + this.status + ", paidAt=" + this.paidAt + ")";
        }
    }
public static PaymentResponse.PaymentResponseBuilder builder() {
        return new PaymentResponse.PaymentResponseBuilder();
    }
public Long getId() {
        return this.id;
    }
public Long getUserId() {
        return this.userId;
    }
public String getUserName() {
        return this.userName;
    }
public Long getGymId() {
        return this.gymId;
    }
public String getGymName() {
        return this.gymName;
    }
public BigDecimal getAmount() {
        return this.amount;
    }
public PaymentStatus getStatus() {
        return this.status;
    }
public LocalDateTime getPaidAt() {
        return this.paidAt;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setUserId(final Long userId) {
        this.userId = userId;
    }
public void setUserName(final String userName) {
        this.userName = userName;
    }
public void setGymId(final Long gymId) {
        this.gymId = gymId;
    }
public void setGymName(final String gymName) {
        this.gymName = gymName;
    }
public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }
public void setStatus(final PaymentStatus status) {
        this.status = status;
    }
public void setPaidAt(final LocalDateTime paidAt) {
        this.paidAt = paidAt;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PaymentResponse)) return false;
        final PaymentResponse other = (PaymentResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$gymId = this.getGymId();
        final java.lang.Object other$gymId = other.getGymId();
        if (this$gymId == null ? other$gymId != null : !this$gymId.equals(other$gymId)) return false;
        final java.lang.Object this$userName = this.getUserName();
        final java.lang.Object other$userName = other.getUserName();
        if (this$userName == null ? other$userName != null : !this$userName.equals(other$userName)) return false;
        final java.lang.Object this$gymName = this.getGymName();
        final java.lang.Object other$gymName = other.getGymName();
        if (this$gymName == null ? other$gymName != null : !this$gymName.equals(other$gymName)) return false;
        final java.lang.Object this$amount = this.getAmount();
        final java.lang.Object other$amount = other.getAmount();
        if (this$amount == null ? other$amount != null : !this$amount.equals(other$amount)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$paidAt = this.getPaidAt();
        final java.lang.Object other$paidAt = other.getPaidAt();
        if (this$paidAt == null ? other$paidAt != null : !this$paidAt.equals(other$paidAt)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PaymentResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $gymId = this.getGymId();
        result = result * PRIME + ($gymId == null ? 43 : $gymId.hashCode());
        final java.lang.Object $userName = this.getUserName();
        result = result * PRIME + ($userName == null ? 43 : $userName.hashCode());
        final java.lang.Object $gymName = this.getGymName();
        result = result * PRIME + ($gymName == null ? 43 : $gymName.hashCode());
        final java.lang.Object $amount = this.getAmount();
        result = result * PRIME + ($amount == null ? 43 : $amount.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $paidAt = this.getPaidAt();
        result = result * PRIME + ($paidAt == null ? 43 : $paidAt.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "PaymentResponse(id=" + this.getId() + ", userId=" + this.getUserId() + ", userName=" + this.getUserName() + ", gymId=" + this.getGymId() + ", gymName=" + this.getGymName() + ", amount=" + this.getAmount() + ", status=" + this.getStatus() + ", paidAt=" + this.getPaidAt() + ")";
    }
}
