// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import jakarta.validation.constraints.NotNull;

public class PaymentStatusRequest {
    @NotNull(message = "Payment ID is required")
    private Long paymentId;
public static class PaymentStatusRequestBuilder {
private Long paymentId;
PaymentStatusRequestBuilder() {
        }
public PaymentStatusRequest.PaymentStatusRequestBuilder paymentId(final Long paymentId) {
            this.paymentId = paymentId;
            return this;
        }
public PaymentStatusRequest build() {
            return new PaymentStatusRequest(this.paymentId);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "PaymentStatusRequest.PaymentStatusRequestBuilder(paymentId=" + this.paymentId + ")";
        }
    }
public static PaymentStatusRequest.PaymentStatusRequestBuilder builder() {
        return new PaymentStatusRequest.PaymentStatusRequestBuilder();
    }
public Long getPaymentId() {
        return this.paymentId;
    }
public void setPaymentId(final Long paymentId) {
        this.paymentId = paymentId;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PaymentStatusRequest)) return false;
        final PaymentStatusRequest other = (PaymentStatusRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$paymentId = this.getPaymentId();
        final java.lang.Object other$paymentId = other.getPaymentId();
        if (this$paymentId == null ? other$paymentId != null : !this$paymentId.equals(other$paymentId)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PaymentStatusRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $paymentId = this.getPaymentId();
        result = result * PRIME + ($paymentId == null ? 43 : $paymentId.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "PaymentStatusRequest(paymentId=" + this.getPaymentId() + ")";
    }
public PaymentStatusRequest() {
    }
public PaymentStatusRequest(final Long paymentId) {
        this.paymentId = paymentId;
    }
}
