// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import java.math.BigDecimal;

public class PaymentRequest {
    @NotNull(message = "Gym ID is required")
    private Long gymId;
    @NotNull(message = "Amount is required")
    @DecimalMin(value = "0.01", message = "Amount must be greater than 0")
    @Positive(message = "Amount must be positive")
    private BigDecimal amount;
    private String description; // e.g., "Monthly membership - PRO"
    /**
     * Factory Pattern: determines which PaymentProcessor to use.
     * Supported values: "MOCK" (default), "STRIPE"
     */
    private String paymentType;
private static String $default$paymentType() {
        return "MOCK";
    }
public static class PaymentRequestBuilder {
private Long gymId;
private BigDecimal amount;
private String description;
private boolean paymentType$set;
private String paymentType$value;
PaymentRequestBuilder() {
        }
public PaymentRequest.PaymentRequestBuilder gymId(final Long gymId) {
            this.gymId = gymId;
            return this;
        }
public PaymentRequest.PaymentRequestBuilder amount(final BigDecimal amount) {
            this.amount = amount;
            return this;
        }
public PaymentRequest.PaymentRequestBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * Factory Pattern: determines which PaymentProcessor to use.
         * Supported values: "MOCK" (default), "STRIPE"
         * @return {@code this}.
         */
public PaymentRequest.PaymentRequestBuilder paymentType(final String paymentType) {
            this.paymentType$value = paymentType;
            paymentType$set = true;
            return this;
        }
public PaymentRequest build() {
            String paymentType$value = this.paymentType$value;
            if (!this.paymentType$set) paymentType$value = PaymentRequest.$default$paymentType();
            return new PaymentRequest(this.gymId, this.amount, this.description, paymentType$value);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "PaymentRequest.PaymentRequestBuilder(gymId=" + this.gymId + ", amount=" + this.amount + ", description=" + this.description + ", paymentType$value=" + this.paymentType$value + ")";
        }
    }
public static PaymentRequest.PaymentRequestBuilder builder() {
        return new PaymentRequest.PaymentRequestBuilder();
    }
public Long getGymId() {
        return this.gymId;
    }
public BigDecimal getAmount() {
        return this.amount;
    }
public String getDescription() {
        return this.description;
    }

    /**
     * Factory Pattern: determines which PaymentProcessor to use.
     * Supported values: "MOCK" (default), "STRIPE"
     */
public String getPaymentType() {
        return this.paymentType;
    }
public void setGymId(final Long gymId) {
        this.gymId = gymId;
    }
public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }
public void setDescription(final String description) {
        this.description = description;
    }

    /**
     * Factory Pattern: determines which PaymentProcessor to use.
     * Supported values: "MOCK" (default), "STRIPE"
     */
public void setPaymentType(final String paymentType) {
        this.paymentType = paymentType;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PaymentRequest)) return false;
        final PaymentRequest other = (PaymentRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$gymId = this.getGymId();
        final java.lang.Object other$gymId = other.getGymId();
        if (this$gymId == null ? other$gymId != null : !this$gymId.equals(other$gymId)) return false;
        final java.lang.Object this$amount = this.getAmount();
        final java.lang.Object other$amount = other.getAmount();
        if (this$amount == null ? other$amount != null : !this$amount.equals(other$amount)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$paymentType = this.getPaymentType();
        final java.lang.Object other$paymentType = other.getPaymentType();
        if (this$paymentType == null ? other$paymentType != null : !this$paymentType.equals(other$paymentType)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PaymentRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $gymId = this.getGymId();
        result = result * PRIME + ($gymId == null ? 43 : $gymId.hashCode());
        final java.lang.Object $amount = this.getAmount();
        result = result * PRIME + ($amount == null ? 43 : $amount.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $paymentType = this.getPaymentType();
        result = result * PRIME + ($paymentType == null ? 43 : $paymentType.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "PaymentRequest(gymId=" + this.getGymId() + ", amount=" + this.getAmount() + ", description=" + this.getDescription() + ", paymentType=" + this.getPaymentType() + ")";
    }
public PaymentRequest() {
        this.paymentType = PaymentRequest.$default$paymentType();
    }

    /**
     * Creates a new {@code PaymentRequest} instance.
     *
     * @param gymId
     * @param amount
     * @param description
     * @param paymentType Factory Pattern: determines which PaymentProcessor to use.
     * Supported values: "MOCK" (default), "STRIPE"
     */
public PaymentRequest(final Long gymId, final BigDecimal amount, final String description, final String paymentType) {
        this.gymId = gymId;
        this.amount = amount;
        this.description = description;
        this.paymentType = paymentType;
    }
}
