// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import java.time.LocalDate;

public class StreakResponse {
    private Long userId;
    private Integer streakCount;
    private Integer pauseTokensRemaining;
    private LocalDate lastActivityDate;
StreakResponse(final Long userId, final Integer streakCount, final Integer pauseTokensRemaining, final LocalDate lastActivityDate) {
        this.userId = userId;
        this.streakCount = streakCount;
        this.pauseTokensRemaining = pauseTokensRemaining;
        this.lastActivityDate = lastActivityDate;
    }
public static class StreakResponseBuilder {
private Long userId;
private Integer streakCount;
private Integer pauseTokensRemaining;
private LocalDate lastActivityDate;
StreakResponseBuilder() {
        }
public StreakResponse.StreakResponseBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }
public StreakResponse.StreakResponseBuilder streakCount(final Integer streakCount) {
            this.streakCount = streakCount;
            return this;
        }
public StreakResponse.StreakResponseBuilder pauseTokensRemaining(final Integer pauseTokensRemaining) {
            this.pauseTokensRemaining = pauseTokensRemaining;
            return this;
        }
public StreakResponse.StreakResponseBuilder lastActivityDate(final LocalDate lastActivityDate) {
            this.lastActivityDate = lastActivityDate;
            return this;
        }
public StreakResponse build() {
            return new StreakResponse(this.userId, this.streakCount, this.pauseTokensRemaining, this.lastActivityDate);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "StreakResponse.StreakResponseBuilder(userId=" + this.userId + ", streakCount=" + this.streakCount + ", pauseTokensRemaining=" + this.pauseTokensRemaining + ", lastActivityDate=" + this.lastActivityDate + ")";
        }
    }
public static StreakResponse.StreakResponseBuilder builder() {
        return new StreakResponse.StreakResponseBuilder();
    }
public Long getUserId() {
        return this.userId;
    }
public Integer getStreakCount() {
        return this.streakCount;
    }
public Integer getPauseTokensRemaining() {
        return this.pauseTokensRemaining;
    }
public LocalDate getLastActivityDate() {
        return this.lastActivityDate;
    }
public void setUserId(final Long userId) {
        this.userId = userId;
    }
public void setStreakCount(final Integer streakCount) {
        this.streakCount = streakCount;
    }
public void setPauseTokensRemaining(final Integer pauseTokensRemaining) {
        this.pauseTokensRemaining = pauseTokensRemaining;
    }
public void setLastActivityDate(final LocalDate lastActivityDate) {
        this.lastActivityDate = lastActivityDate;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof StreakResponse)) return false;
        final StreakResponse other = (StreakResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$streakCount = this.getStreakCount();
        final java.lang.Object other$streakCount = other.getStreakCount();
        if (this$streakCount == null ? other$streakCount != null : !this$streakCount.equals(other$streakCount)) return false;
        final java.lang.Object this$pauseTokensRemaining = this.getPauseTokensRemaining();
        final java.lang.Object other$pauseTokensRemaining = other.getPauseTokensRemaining();
        if (this$pauseTokensRemaining == null ? other$pauseTokensRemaining != null : !this$pauseTokensRemaining.equals(other$pauseTokensRemaining)) return false;
        final java.lang.Object this$lastActivityDate = this.getLastActivityDate();
        final java.lang.Object other$lastActivityDate = other.getLastActivityDate();
        if (this$lastActivityDate == null ? other$lastActivityDate != null : !this$lastActivityDate.equals(other$lastActivityDate)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof StreakResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $streakCount = this.getStreakCount();
        result = result * PRIME + ($streakCount == null ? 43 : $streakCount.hashCode());
        final java.lang.Object $pauseTokensRemaining = this.getPauseTokensRemaining();
        result = result * PRIME + ($pauseTokensRemaining == null ? 43 : $pauseTokensRemaining.hashCode());
        final java.lang.Object $lastActivityDate = this.getLastActivityDate();
        result = result * PRIME + ($lastActivityDate == null ? 43 : $lastActivityDate.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "StreakResponse(userId=" + this.getUserId() + ", streakCount=" + this.getStreakCount() + ", pauseTokensRemaining=" + this.getPauseTokensRemaining() + ", lastActivityDate=" + this.getLastActivityDate() + ")";
    }
}
