// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

public class TrainerResponse {
    private Long id;
    private Long userId;
    private String trainerName;
    private Long gymId;
    private String gymName;
    private Integer experience;
    private String specialization;
    private Double rating;
    private Long ratingCount;
TrainerResponse(final Long id, final Long userId, final String trainerName, final Long gymId, final String gymName, final Integer experience, final String specialization, final Double rating, final Long ratingCount) {
        this.id = id;
        this.userId = userId;
        this.trainerName = trainerName;
        this.gymId = gymId;
        this.gymName = gymName;
        this.experience = experience;
        this.specialization = specialization;
        this.rating = rating;
        this.ratingCount = ratingCount;
    }
public static class TrainerResponseBuilder {
private Long id;
private Long userId;
private String trainerName;
private Long gymId;
private String gymName;
private Integer experience;
private String specialization;
private Double rating;
private Long ratingCount;
TrainerResponseBuilder() {
        }
public TrainerResponse.TrainerResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }
public TrainerResponse.TrainerResponseBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }
public TrainerResponse.TrainerResponseBuilder trainerName(final String trainerName) {
            this.trainerName = trainerName;
            return this;
        }
public TrainerResponse.TrainerResponseBuilder gymId(final Long gymId) {
            this.gymId = gymId;
            return this;
        }
public TrainerResponse.TrainerResponseBuilder gymName(final String gymName) {
            this.gymName = gymName;
            return this;
        }
public TrainerResponse.TrainerResponseBuilder experience(final Integer experience) {
            this.experience = experience;
            return this;
        }
public TrainerResponse.TrainerResponseBuilder specialization(final String specialization) {
            this.specialization = specialization;
            return this;
        }
public TrainerResponse.TrainerResponseBuilder rating(final Double rating) {
            this.rating = rating;
            return this;
        }
public TrainerResponse.TrainerResponseBuilder ratingCount(final Long ratingCount) {
            this.ratingCount = ratingCount;
            return this;
        }
public TrainerResponse build() {
            return new TrainerResponse(this.id, this.userId, this.trainerName, this.gymId, this.gymName, this.experience, this.specialization, this.rating, this.ratingCount);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "TrainerResponse.TrainerResponseBuilder(id=" + this.id + ", userId=" + this.userId + ", trainerName=" + this.trainerName + ", gymId=" + this.gymId + ", gymName=" + this.gymName + ", experience=" + this.experience + ", specialization=" + this.specialization + ", rating=" + this.rating + ", ratingCount=" + this.ratingCount + ")";
        }
    }
public static TrainerResponse.TrainerResponseBuilder builder() {
        return new TrainerResponse.TrainerResponseBuilder();
    }
public Long getId() {
        return this.id;
    }
public Long getUserId() {
        return this.userId;
    }
public String getTrainerName() {
        return this.trainerName;
    }
public Long getGymId() {
        return this.gymId;
    }
public String getGymName() {
        return this.gymName;
    }
public Integer getExperience() {
        return this.experience;
    }
public String getSpecialization() {
        return this.specialization;
    }
public Double getRating() {
        return this.rating;
    }
public Long getRatingCount() {
        return this.ratingCount;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setUserId(final Long userId) {
        this.userId = userId;
    }
public void setTrainerName(final String trainerName) {
        this.trainerName = trainerName;
    }
public void setGymId(final Long gymId) {
        this.gymId = gymId;
    }
public void setGymName(final String gymName) {
        this.gymName = gymName;
    }
public void setExperience(final Integer experience) {
        this.experience = experience;
    }
public void setSpecialization(final String specialization) {
        this.specialization = specialization;
    }
public void setRating(final Double rating) {
        this.rating = rating;
    }
public void setRatingCount(final Long ratingCount) {
        this.ratingCount = ratingCount;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TrainerResponse)) return false;
        final TrainerResponse other = (TrainerResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$gymId = this.getGymId();
        final java.lang.Object other$gymId = other.getGymId();
        if (this$gymId == null ? other$gymId != null : !this$gymId.equals(other$gymId)) return false;
        final java.lang.Object this$experience = this.getExperience();
        final java.lang.Object other$experience = other.getExperience();
        if (this$experience == null ? other$experience != null : !this$experience.equals(other$experience)) return false;
        final java.lang.Object this$rating = this.getRating();
        final java.lang.Object other$rating = other.getRating();
        if (this$rating == null ? other$rating != null : !this$rating.equals(other$rating)) return false;
        final java.lang.Object this$ratingCount = this.getRatingCount();
        final java.lang.Object other$ratingCount = other.getRatingCount();
        if (this$ratingCount == null ? other$ratingCount != null : !this$ratingCount.equals(other$ratingCount)) return false;
        final java.lang.Object this$trainerName = this.getTrainerName();
        final java.lang.Object other$trainerName = other.getTrainerName();
        if (this$trainerName == null ? other$trainerName != null : !this$trainerName.equals(other$trainerName)) return false;
        final java.lang.Object this$gymName = this.getGymName();
        final java.lang.Object other$gymName = other.getGymName();
        if (this$gymName == null ? other$gymName != null : !this$gymName.equals(other$gymName)) return false;
        final java.lang.Object this$specialization = this.getSpecialization();
        final java.lang.Object other$specialization = other.getSpecialization();
        if (this$specialization == null ? other$specialization != null : !this$specialization.equals(other$specialization)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TrainerResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $gymId = this.getGymId();
        result = result * PRIME + ($gymId == null ? 43 : $gymId.hashCode());
        final java.lang.Object $experience = this.getExperience();
        result = result * PRIME + ($experience == null ? 43 : $experience.hashCode());
        final java.lang.Object $rating = this.getRating();
        result = result * PRIME + ($rating == null ? 43 : $rating.hashCode());
        final java.lang.Object $ratingCount = this.getRatingCount();
        result = result * PRIME + ($ratingCount == null ? 43 : $ratingCount.hashCode());
        final java.lang.Object $trainerName = this.getTrainerName();
        result = result * PRIME + ($trainerName == null ? 43 : $trainerName.hashCode());
        final java.lang.Object $gymName = this.getGymName();
        result = result * PRIME + ($gymName == null ? 43 : $gymName.hashCode());
        final java.lang.Object $specialization = this.getSpecialization();
        result = result * PRIME + ($specialization == null ? 43 : $specialization.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "TrainerResponse(id=" + this.getId() + ", userId=" + this.getUserId() + ", trainerName=" + this.getTrainerName() + ", gymId=" + this.getGymId() + ", gymName=" + this.getGymName() + ", experience=" + this.getExperience() + ", specialization=" + this.getSpecialization() + ", rating=" + this.getRating() + ", ratingCount=" + this.getRatingCount() + ")";
    }
}
