// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

public class TrainerProfileUpdateRequest {
    @NotNull
    private Long gymId;
    @NotNull
    private Integer experience;
    @NotBlank
    private String specialization;
public TrainerProfileUpdateRequest() {
    }
public Long getGymId() {
        return this.gymId;
    }
public Integer getExperience() {
        return this.experience;
    }
public String getSpecialization() {
        return this.specialization;
    }
public void setGymId(final Long gymId) {
        this.gymId = gymId;
    }
public void setExperience(final Integer experience) {
        this.experience = experience;
    }
public void setSpecialization(final String specialization) {
        this.specialization = specialization;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TrainerProfileUpdateRequest)) return false;
        final TrainerProfileUpdateRequest other = (TrainerProfileUpdateRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$gymId = this.getGymId();
        final java.lang.Object other$gymId = other.getGymId();
        if (this$gymId == null ? other$gymId != null : !this$gymId.equals(other$gymId)) return false;
        final java.lang.Object this$experience = this.getExperience();
        final java.lang.Object other$experience = other.getExperience();
        if (this$experience == null ? other$experience != null : !this$experience.equals(other$experience)) return false;
        final java.lang.Object this$specialization = this.getSpecialization();
        final java.lang.Object other$specialization = other.getSpecialization();
        if (this$specialization == null ? other$specialization != null : !this$specialization.equals(other$specialization)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof TrainerProfileUpdateRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $gymId = this.getGymId();
        result = result * PRIME + ($gymId == null ? 43 : $gymId.hashCode());
        final java.lang.Object $experience = this.getExperience();
        result = result * PRIME + ($experience == null ? 43 : $experience.hashCode());
        final java.lang.Object $specialization = this.getSpecialization();
        result = result * PRIME + ($specialization == null ? 43 : $specialization.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "TrainerProfileUpdateRequest(gymId=" + this.getGymId() + ", experience=" + this.getExperience() + ", specialization=" + this.getSpecialization() + ")";
    }
}
