// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import java.math.BigDecimal;
import java.time.LocalDate;

public class WeeklyCaloriesResponse {
    private LocalDate weekStart;
    private LocalDate weekEnd;
    private BigDecimal totalCalories;
WeeklyCaloriesResponse(final LocalDate weekStart, final LocalDate weekEnd, final BigDecimal totalCalories) {
        this.weekStart = weekStart;
        this.weekEnd = weekEnd;
        this.totalCalories = totalCalories;
    }
public static class WeeklyCaloriesResponseBuilder {
private LocalDate weekStart;
private LocalDate weekEnd;
private BigDecimal totalCalories;
WeeklyCaloriesResponseBuilder() {
        }
public WeeklyCaloriesResponse.WeeklyCaloriesResponseBuilder weekStart(final LocalDate weekStart) {
            this.weekStart = weekStart;
            return this;
        }
public WeeklyCaloriesResponse.WeeklyCaloriesResponseBuilder weekEnd(final LocalDate weekEnd) {
            this.weekEnd = weekEnd;
            return this;
        }
public WeeklyCaloriesResponse.WeeklyCaloriesResponseBuilder totalCalories(final BigDecimal totalCalories) {
            this.totalCalories = totalCalories;
            return this;
        }
public WeeklyCaloriesResponse build() {
            return new WeeklyCaloriesResponse(this.weekStart, this.weekEnd, this.totalCalories);
        }

        @java.lang.Override
public java.lang.String toString() {
            return "WeeklyCaloriesResponse.WeeklyCaloriesResponseBuilder(weekStart=" + this.weekStart + ", weekEnd=" + this.weekEnd + ", totalCalories=" + this.totalCalories + ")";
        }
    }
public static WeeklyCaloriesResponse.WeeklyCaloriesResponseBuilder builder() {
        return new WeeklyCaloriesResponse.WeeklyCaloriesResponseBuilder();
    }
public LocalDate getWeekStart() {
        return this.weekStart;
    }
public LocalDate getWeekEnd() {
        return this.weekEnd;
    }
public BigDecimal getTotalCalories() {
        return this.totalCalories;
    }
public void setWeekStart(final LocalDate weekStart) {
        this.weekStart = weekStart;
    }
public void setWeekEnd(final LocalDate weekEnd) {
        this.weekEnd = weekEnd;
    }
public void setTotalCalories(final BigDecimal totalCalories) {
        this.totalCalories = totalCalories;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof WeeklyCaloriesResponse)) return false;
        final WeeklyCaloriesResponse other = (WeeklyCaloriesResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$weekStart = this.getWeekStart();
        final java.lang.Object other$weekStart = other.getWeekStart();
        if (this$weekStart == null ? other$weekStart != null : !this$weekStart.equals(other$weekStart)) return false;
        final java.lang.Object this$weekEnd = this.getWeekEnd();
        final java.lang.Object other$weekEnd = other.getWeekEnd();
        if (this$weekEnd == null ? other$weekEnd != null : !this$weekEnd.equals(other$weekEnd)) return false;
        final java.lang.Object this$totalCalories = this.getTotalCalories();
        final java.lang.Object other$totalCalories = other.getTotalCalories();
        if (this$totalCalories == null ? other$totalCalories != null : !this$totalCalories.equals(other$totalCalories)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof WeeklyCaloriesResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $weekStart = this.getWeekStart();
        result = result * PRIME + ($weekStart == null ? 43 : $weekStart.hashCode());
        final java.lang.Object $weekEnd = this.getWeekEnd();
        result = result * PRIME + ($weekEnd == null ? 43 : $weekEnd.hashCode());
        final java.lang.Object $totalCalories = this.getTotalCalories();
        result = result * PRIME + ($totalCalories == null ? 43 : $totalCalories.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "WeeklyCaloriesResponse(weekStart=" + this.getWeekStart() + ", weekEnd=" + this.getWeekEnd() + ", totalCalories=" + this.getTotalCalories() + ")";
    }
}
