// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class WorkoutResponse {
    private Long id;
    private Long userId;
    private String exerciseName;
    private BigDecimal weight;
    private Integer reps;
    private Integer duration;
    private BigDecimal caloriesBurned;
    private LocalDateTime createdAt;

    public static WorkoutResponseBuilder builder() {
        return new WorkoutResponseBuilder();
    }


    public static class WorkoutResponseBuilder {
        private Long id;
        private Long userId;
        private String exerciseName;
        private BigDecimal weight;
        private Integer reps;
        private Integer duration;
        private BigDecimal caloriesBurned;
        private LocalDateTime createdAt;

        WorkoutResponseBuilder() {
        }

        public WorkoutResponseBuilder id(Long id) {
            this.id = id;
            return this;
        }

        public WorkoutResponseBuilder userId(Long userId) {
            this.userId = userId;
            return this;
        }

        public WorkoutResponseBuilder exerciseName(String exerciseName) {
            this.exerciseName = exerciseName;
            return this;
        }

        public WorkoutResponseBuilder weight(BigDecimal weight) {
            this.weight = weight;
            return this;
        }

        public WorkoutResponseBuilder reps(Integer reps) {
            this.reps = reps;
            return this;
        }

        public WorkoutResponseBuilder duration(Integer duration) {
            this.duration = duration;
            return this;
        }

        public WorkoutResponseBuilder caloriesBurned(BigDecimal caloriesBurned) {
            this.caloriesBurned = caloriesBurned;
            return this;
        }

        public WorkoutResponseBuilder createdAt(LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public WorkoutResponse build() {
            return new WorkoutResponse(this.id, this.userId, this.exerciseName, this.weight, this.reps, this.duration, this.caloriesBurned, this.createdAt);
        }

        public String toString() {
            return "WorkoutResponse.WorkoutResponseBuilder(id=" + this.id + ", userId=" + this.userId + ", exerciseName=" + this.exerciseName + ", weight=" + this.weight + ", reps=" + this.reps + ", duration=" + this.duration + ", caloriesBurned=" + this.caloriesBurned + ", createdAt=" + this.createdAt + ")";
        }
    }
public Long getId() {
        return this.id;
    }
public Long getUserId() {
        return this.userId;
    }
public String getExerciseName() {
        return this.exerciseName;
    }
public BigDecimal getWeight() {
        return this.weight;
    }
public Integer getReps() {
        return this.reps;
    }
public Integer getDuration() {
        return this.duration;
    }
public BigDecimal getCaloriesBurned() {
        return this.caloriesBurned;
    }
public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }
public void setId(final Long id) {
        this.id = id;
    }
public void setUserId(final Long userId) {
        this.userId = userId;
    }
public void setExerciseName(final String exerciseName) {
        this.exerciseName = exerciseName;
    }
public void setWeight(final BigDecimal weight) {
        this.weight = weight;
    }
public void setReps(final Integer reps) {
        this.reps = reps;
    }
public void setDuration(final Integer duration) {
        this.duration = duration;
    }
public void setCaloriesBurned(final BigDecimal caloriesBurned) {
        this.caloriesBurned = caloriesBurned;
    }
public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof WorkoutResponse)) return false;
        final WorkoutResponse other = (WorkoutResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$reps = this.getReps();
        final java.lang.Object other$reps = other.getReps();
        if (this$reps == null ? other$reps != null : !this$reps.equals(other$reps)) return false;
        final java.lang.Object this$duration = this.getDuration();
        final java.lang.Object other$duration = other.getDuration();
        if (this$duration == null ? other$duration != null : !this$duration.equals(other$duration)) return false;
        final java.lang.Object this$exerciseName = this.getExerciseName();
        final java.lang.Object other$exerciseName = other.getExerciseName();
        if (this$exerciseName == null ? other$exerciseName != null : !this$exerciseName.equals(other$exerciseName)) return false;
        final java.lang.Object this$weight = this.getWeight();
        final java.lang.Object other$weight = other.getWeight();
        if (this$weight == null ? other$weight != null : !this$weight.equals(other$weight)) return false;
        final java.lang.Object this$caloriesBurned = this.getCaloriesBurned();
        final java.lang.Object other$caloriesBurned = other.getCaloriesBurned();
        if (this$caloriesBurned == null ? other$caloriesBurned != null : !this$caloriesBurned.equals(other$caloriesBurned)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof WorkoutResponse;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $reps = this.getReps();
        result = result * PRIME + ($reps == null ? 43 : $reps.hashCode());
        final java.lang.Object $duration = this.getDuration();
        result = result * PRIME + ($duration == null ? 43 : $duration.hashCode());
        final java.lang.Object $exerciseName = this.getExerciseName();
        result = result * PRIME + ($exerciseName == null ? 43 : $exerciseName.hashCode());
        final java.lang.Object $weight = this.getWeight();
        result = result * PRIME + ($weight == null ? 43 : $weight.hashCode());
        final java.lang.Object $caloriesBurned = this.getCaloriesBurned();
        result = result * PRIME + ($caloriesBurned == null ? 43 : $caloriesBurned.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "WorkoutResponse(id=" + this.getId() + ", userId=" + this.getUserId() + ", exerciseName=" + this.getExerciseName() + ", weight=" + this.getWeight() + ", reps=" + this.getReps() + ", duration=" + this.getDuration() + ", caloriesBurned=" + this.getCaloriesBurned() + ", createdAt=" + this.getCreatedAt() + ")";
    }
public WorkoutResponse() {
    }
public WorkoutResponse(final Long id, final Long userId, final String exerciseName, final BigDecimal weight, final Integer reps, final Integer duration, final BigDecimal caloriesBurned, final LocalDateTime createdAt) {
        this.id = id;
        this.userId = userId;
        this.exerciseName = exerciseName;
        this.weight = weight;
        this.reps = reps;
        this.duration = duration;
        this.caloriesBurned = caloriesBurned;
        this.createdAt = createdAt;
    }
}
