// Generated by delombok at Wed Apr 22 08:22:56 IST 2026
package com.fitconnect.dto;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;

public class WorkoutRequest {
    @NotBlank
    private String exerciseName;
    @NotNull
    @Min(0)
    private BigDecimal weight;
    @NotNull
    @Min(0)
    private Integer reps;
    @NotNull
    @Min(1)
    private Integer duration;
public WorkoutRequest() {
    }
public String getExerciseName() {
        return this.exerciseName;
    }
public BigDecimal getWeight() {
        return this.weight;
    }
public Integer getReps() {
        return this.reps;
    }
public Integer getDuration() {
        return this.duration;
    }
public void setExerciseName(final String exerciseName) {
        this.exerciseName = exerciseName;
    }
public void setWeight(final BigDecimal weight) {
        this.weight = weight;
    }
public void setReps(final Integer reps) {
        this.reps = reps;
    }
public void setDuration(final Integer duration) {
        this.duration = duration;
    }

    @java.lang.Override
public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof WorkoutRequest)) return false;
        final WorkoutRequest other = (WorkoutRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$reps = this.getReps();
        final java.lang.Object other$reps = other.getReps();
        if (this$reps == null ? other$reps != null : !this$reps.equals(other$reps)) return false;
        final java.lang.Object this$duration = this.getDuration();
        final java.lang.Object other$duration = other.getDuration();
        if (this$duration == null ? other$duration != null : !this$duration.equals(other$duration)) return false;
        final java.lang.Object this$exerciseName = this.getExerciseName();
        final java.lang.Object other$exerciseName = other.getExerciseName();
        if (this$exerciseName == null ? other$exerciseName != null : !this$exerciseName.equals(other$exerciseName)) return false;
        final java.lang.Object this$weight = this.getWeight();
        final java.lang.Object other$weight = other.getWeight();
        if (this$weight == null ? other$weight != null : !this$weight.equals(other$weight)) return false;
        return true;
    }
protected boolean canEqual(final java.lang.Object other) {
        return other instanceof WorkoutRequest;
    }

    @java.lang.Override
public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $reps = this.getReps();
        result = result * PRIME + ($reps == null ? 43 : $reps.hashCode());
        final java.lang.Object $duration = this.getDuration();
        result = result * PRIME + ($duration == null ? 43 : $duration.hashCode());
        final java.lang.Object $exerciseName = this.getExerciseName();
        result = result * PRIME + ($exerciseName == null ? 43 : $exerciseName.hashCode());
        final java.lang.Object $weight = this.getWeight();
        result = result * PRIME + ($weight == null ? 43 : $weight.hashCode());
        return result;
    }

    @java.lang.Override
public java.lang.String toString() {
        return "WorkoutRequest(exerciseName=" + this.getExerciseName() + ", weight=" + this.getWeight() + ", reps=" + this.getReps() + ", duration=" + this.getDuration() + ")";
    }
}
